### ISSUE TITLE
Feature request: Add bindings for `Uint32::Value()` and `Int32::Value()`

### ISSUE THREAD

**Issue by aapoalas** [denoland/rusty_v8#1027]
`Uint32` and `Int32` classes have their own `Value()` methods that return, as one might expect, `u32` and `i32` respectively.

The difference between using the inherited `Integer::Value()` isn't much, but it would offer the slightest bit of more performance.

**Comment by bartlomieju** [comment]
Seems reasonable, PRs are welcome.
