### ISSUE TITLE
On release publish target/debug/gn_out/obj/librusty_v8.a to github releases

### ISSUE THREAD

**Issue by ry** [denoland/rusty_v8#107]
This will allow us to have a binary build at some point.

**Comment by Brooooooklyn** [comment]
We have done something similar in [skia-binaries](https://github.com/rust-skia/skia-binaries/releases/tag/0.21.2)
Maybe the [CI configuration](https://github.com/rust-skia/rust-skia/blob/release/azure-pipelines-build-target.yml) can help

**Comment by ry** [comment]
done in https://github.com/denoland/rusty_v8/commit/35cc92caab28d4f17133c9d5f9d07eb399ce6051
