### ISSUE TITLE
FunctionCallbackInfo::Callee not exposed from v8

### ISSUE THREAD

**Issue by BigBadE** [denoland/rusty_v8#1107]
Rusty_v8 is missing a binding for FunctionICallbackInfo::Callee, as shown in https://v8docs.nodesource.com/node-0.12/dd/d0d/classv8_1_1_function_callback_info.html#ad8dd7c0877fff6858758f6e36e15ef6f

I'll gladly add this myself, just wanted to make an issue in case it's already in another PR or someone else is doing it.

**Comment by BigBadE** [comment]
Attempted to add it myself, gn error'd on a "unused variable" that is used. Couldn't find a solution, so I couldn't build https://github.com/BigBadE/rusty_v8, but it looks correct.

**Comment by bartlomieju** [comment]
@BigBadE please open a PR, it might be easier to advise

**Comment by BigBadE** [comment]
@bartlomieju My mistake, I thought I opened a PR, it's now at #1108

**Comment by WingZer0o** [comment]
Is this currently being worked on?

**Comment by bartlomieju** [comment]
@WingZer0o doesn't look like it; PRs are welcome.

**Comment by WingZer0o** [comment]
@BigBadE @bartlomieju  is this link to version of Node 0.12? If we attempt to navigate to the code in `v8.h` which is the file that is suppose to contain this, we can see that this is now a include file that contains an include to `v8-function-callback.h which no longer has the protected attribute `kCalleeIndex` 
 
```c++
  friend class internal::FunctionCallbackArguments;
  friend class internal::CustomArguments<FunctionCallbackInfo>;
  friend class debug::ConsoleCallArguments;
  static const int kHolderIndex = 0;
  static const int kIsolateIndex = 1;
  static const int kReturnValueDefaultValueIndex = 2;
  static const int kReturnValueIndex = 3;
  static const int kDataIndex = 4;
  static const int kNewTargetIndex = 5;
```

which was being used by 
```c++
template<typename T>
 [Local](https://v8docs.nodesource.com/node-0.12/d3/dd5/classv8_1_1_handle.html#afb872edb4aac7ba55f0da004113aa2b0)<[Function](https://v8docs.nodesource.com/node-0.12/d5/d54/classv8_1_1_function.html)> [FunctionCallbackInfo](https://v8docs.nodesource.com/node-0.12/d3/dd5/classv8_1_1_handle.html#a76786e6fa2d0eac5e2d4f647659d0d23)<T>::[Callee](https://v8docs.nodesource.com/node-0.12/dd/d0d/classv8_1_1_function_callback_info.html#ad8dd7c0877fff6858758f6e36e15ef6f)() const {
   return [Local](https://v8docs.nodesource.com/node-0.12/d3/dd5/classv8_1_1_handle.html#afb872edb4aac7ba55f0da004113aa2b0)<[Function](https://v8docs.nodesource.com/node-0.12/d5/d54/classv8_1_1_function.html)>(reinterpret_cast<[Function](https://v8docs.nodesource.com/node-0.12/d5/d54/classv8_1_1_function.html)*>(
       &[implicit_args_](https://v8docs.nodesource.com/node-0.12/dd/d0d/classv8_1_1_function_callback_info.html#a884fafda3a30156603cd614aa474be5f)[[kCalleeIndex](https://v8docs.nodesource.com/node-0.12/dd/d0d/classv8_1_1_function_callback_info.html#a4c0abdd47ab44ad2f8823708cc845818)]));
 }
```

Is this something that was removed from v8 in its entirety? Perhaps something @bartlomieju could shed some light on.

**Comment by bartlomieju** [comment]
Good point @WingZer0o; I cannot find `Callee` in `v8/include/` directory at all. It might have indeed been removed since then. I guess this issue is now invalid then. Thanks for looking into this anyway!

**Comment by WingZer0o** [comment]
No probs.
