### ISSUE TITLE
Add note about cURL

### ISSUE THREAD

**Issue by Fabizocker456** [denoland/rusty_v8#1111]
This crate cannot be installed without curl, it would be nice to add a notice to README.md and/or the crates.io to prevent others from wasting these 30 minutes like I just did.

**Comment by bartlomieju** [comment]
Makes sense, PRs are very welcome!

**Comment by gutenfries** [comment]
@Fabizocker456, is this satisfactory?

**Comment by Fabizocker456** [comment]
Thanks, that's perfect

**Comment by bartlomieju** [comment]
Done in #1111
