### ISSUE TITLE
Create native node addon using v8

### ISSUE THREAD

**Issue by universalmind303** [denoland/rusty_v8#1130]
I am trying to use the v8 crate to create a native node addon. (I know there is `n-api` but for performance reasons, I'd like to use the v8 engine directly instead of n-api. Is this something that is possible via this crate? 

Following [this tutorial](https://nodejs.org/api/addons.html#hello-world) It looks like I can do everything except call the macros `NODE_SET_METHOD` and `NODE_MODULE`.

**Comment by bartlomieju** [comment]
You should be able to do that - if you look at these functions (they are not really macros) you will see that they just call for V8 APIs that should be already available in rusty_v8, eg:

```
inline void NODE_SET_METHOD(v8::Local<v8::Template> recv,
                            const char* name,
                            v8::FunctionCallback callback) {
  v8::Isolate* isolate = v8::Isolate::GetCurrent();
  v8::HandleScope handle_scope(isolate);
  v8::Local<v8::FunctionTemplate> t = v8::FunctionTemplate::New(isolate,
                                                                callback);
  v8::Local<v8::String> fn_name = v8::String::NewFromUtf8(isolate, name,
      v8::NewStringType::kInternalized).ToLocalChecked();
  t->SetClassName(fn_name);
  recv->Set(fn_name, t);
}
```
