### ISSUE TITLE
Test/Assert on test_api.rs failed because "icudtl.dat" is not included.

### ISSUE THREAD

**Issue by reyman** [denoland/rusty_v8#1145]
Hi,

I'm trying to compile v8 from source using v.49 version of rusty. 

After compilation, test failed due to :  https://github.com/denoland/rusty_v8/blob/v0.49.0/tests/test_api.rs#L31 

```
   Compiling v8 v0.49.0 (/tmp/guix-build-rust-v8-0.49.0.drv-0/v8-0.49.0)
error: couldn't read tests/../third_party/icu/common/icudtl.dat: No such file or directory (os error 2)
  --> tests/test_api.rs:34:41
   |
34 |       assert!(v8::icu::set_common_data_71(align_data::include_aligned!(
   |  _________________________________________^
35 | |       align_data::Align16,
36 | |       "../third_party/icu/common/icudtl.dat"
37 | |     ))
   | |_____^
   |
   = note: this error originates in the macro `include_bytes` (in Nightly builds, run with -Z macro-backtrace for more info)

```

I check and the file clearly don't exist, because  `/third_party/icu/common/icudtl.dat` is excluded from crates : 
https://github.com/denoland/rusty_v8/blob/v0.49.0/Cargo.toml#L44

Is there a way to desactivate this test ? is it normal ?

**Comment by egovelox** [comment]
Hi,

I fixed this error like so :

- [First cloning the v8 repo](https://v8.dev/docs/source-code)

- then just copying the ``icu`` folder from v8 into the deno ``third_party`` directory :
```bash
cp -r v8/third_party/icu rusty_v8/third_party/
```
