### ISSUE TITLE
Global::reset is documented but doesn't exist

### ISSUE THREAD

**Issue by ldanilek** [denoland/rusty_v8#1152]
The docstring here https://docs.rs/rusty_v8/latest/rusty_v8/struct.Global.html says 

```
a global handle remains valid until it is explicitly disposed using reset()
```

however, it appears the `reset()` function is gone. It last existed in version 0.6.0: https://docs.rs/rusty_v8/0.6.0/rusty_v8/struct.Global.html#method.reset and was deleted in https://github.com/denoland/rusty_v8/commit/c13625148f5d049827a932de9df4a714571cd54d

How does one mark a Global so it can be garbage collected? I would guess this is handled by the `impl Drop`, but the docstring is confusing me.

**Comment by bartlomieju** [comment]
I've opened #1153 which should address it. Indeed global handle is disposed when it is dropped.
