### ISSUE TITLE
How to resolve a promise from tokio task?

### ISSUE THREAD

**Issue by boohba** [denoland/rusty_v8#1177]
I'm trying to implement a function that would "delay the execution" by specified number of milliseconds. The problem is that I cannot find a way to access _scope_ from the tokio task. Is there a way to accomplish this?

```js
async function test() {
    await delay(5000);
}
```

```rust
fn callback(scope: &mut v8::HandleScope, args: v8::FunctionCallbackArguments, mut ret: v8::ReturnValue) {
    let resolver = v8::PromiseResolver::new(scope).unwrap();

    let millis: v8::Local<v8::Integer> = unsafe { std::mem::transmute(args.get(0)) };

    tokio::task::spawn_local(async move {
        tokio::time::sleep(Duration::from_millis(millis.value() as _)).await;

        // how do I access scope?
    });

    ret.set(unsafe { std::mem::transmute(resolver.get_promise(scope)) });
}
```

**Comment by andreubotella** [comment]
The `HandleScope` pointed to by `scope` isn't guaranteed to remain alive after the end of the function scope, so you can't access it from an async task which will run after the function ends. You need to create a separate scope inside it.

If you have access to a `&mut Isolate` and to a handle to the same `Context` under which you're running, you can create a scope with `v8::ContextScope::new(v8::HandleScope::new(isolate), context)`. You could achieve this by storing a `Rc<RefCell<OwnedIsolate>>` and a `v8::Global<v8::Context>` in statics, for example.

In any case, doing this isn't easy. And the deno_core crate provides you an interface over V8 that abstracts over the interaction with Rust future executors for you, so you can define "ops" like:
```rust
#[op]
async fn delay(msecs: usize) {
  tokio::time::sleep(Duration::from_millis(millis)).await;
}
```
and use them like
```js
async function test() {
  await Deno.core.ops.op_delay(5000);
}
```

**Comment by boohba** [comment]
The following JS function works as expected.
```JS
async function test() {
    return "Hello, World!";
}
```

However, it fails (`Function::call` returns `None`) if I try to use my `delay` op.
```JS
async function test() {
    await Deno.core.ops.op_delay(5000);

    return "Hello, World!";
}
```

The Rust code:
```Rust
fn main() {
    let mut runtime = JsRuntime::new(RuntimeOptions {
        extensions: vec![Extension::builder("test")
            .ops(vec![delay::decl()])
            .build()],
        ..Default::default()
    });

    #[op(fast)]
    async fn delay(millis: u64) {
        tokio::time::sleep(std::time::Duration::from_millis(millis)).await;
    }

    let handle_scope = &mut runtime.handle_scope();
    let context = v8::Context::new(handle_scope);
    let scope = &mut v8::ContextScope::new(handle_scope, context);
    let global = context.global(scope);

    let code = v8::String::new(scope, include_str!("../test.js")).unwrap();
    let script = v8::Script::compile(scope, code, None).unwrap();
    script.run(scope).unwrap();

    let name = v8::String::new(scope, "test").unwrap();
    let func: v8::Local<v8::Function> = unsafe { std::mem::transmute(global.get(scope, name.into()).unwrap()) };
    let promise: v8::Local<v8::Promise> = unsafe { std::mem::transmute(func.call(scope, global.into(), &[]).unwrap()) };

    println!("{:?}", promise.state());
    if matches!(promise.state(), PromiseState::Fulfilled) {
        println!("{}", promise.result(scope).to_rust_string_lossy(scope));
    }
}
```

What am I doing wrong?

**Comment by graham** [comment]
@andreubotella

Any chance you could point to the place where this is occurring? I'm having some trouble finding exactly where this happens within the magic of the deno_core lib :).

I've tried a couple combinations of creating another context as you mentioned but I can't seem to get the right combo.

In my situation, I'd like to have multiple JS promises awaiting resolution at the same time, but have those promises resolved in rust, something like this:

```rust

fn main() {
    let mut pending_promises: Arc<Mutex<Vec<v8::Local<'_, v8::PromiseResolver>>>> =
        Arc::new(Mutex::new(Vec::new()));

    let platform = v8::new_default_platform(0, false).make_shared();
    v8::V8::initialize_platform(platform);
    v8::V8::initialize();

    let mut isolate = v8::Isolate::new(v8::CreateParams::default());

    let mut handle_scope = v8::HandleScope::new(&mut isolate);
    let global = v8::ObjectTemplate::new(&mut handle_scope);

    global.set(
        v8::String::new(&mut handle_scope, "sleep_a_little")
            .unwrap()
            .into(),
        v8::FunctionTemplate::new(
            &mut handle_scope,
            |mut scope: &mut v8::HandleScope<'_>,
             mut args: v8::FunctionCallbackArguments,
             mut retval: v8::ReturnValue| {
                let resolver = v8::PromiseResolver::new(&mut scope).unwrap();
                let promise = resolver.get_promise(&mut scope);
                retval.set(promise.into());

                // Save the resolver somehow?
            },
        )
        .into(),
    );

    let context = v8::Context::new_from_template(&mut handle_scope, global);
    let mut context_scope = v8::ContextScope::new(&mut handle_scope, context);

    // Compile a module and run some javascript code that calls "sleep_a_little"
    // Do some stuff, resolve the promise, call `perform_microtask_checkpoint`
}
```

I wasn't able to determine how to create a resolver that was allowed to leave the closure, any input or information would be greatly appreciated. (I understand this is tough).

**Comment by andreubotella** [comment]
With [`v8::FunctionBuilder::data`](https://docs.rs/v8/latest/v8/struct.FunctionBuilder.html#method.data) you can associate some arbitrary JS value to a function, which you can then get from inside it with [`FunctionCallbackArguments::data`](https://docs.rs/v8/latest/v8/struct.FunctionCallbackArguments.html#method.data). Using [`v8::External`](https://docs.rs/v8/latest/v8/struct.External.html), this value can be a pointer to Rust memory which is opaque to JS (it would look like a regular empty object).

In order to do something like this, you would have to make sure that there's some existing reference to the pending promises while the isolate is alive, so the pointer doesn't get invalidated, and use unsafe to dereference it from the function.

**Comment by graham** [comment]
I'm sure it will take some trial and error but this is exactly what I needed, thank you very much!
