### ISSUE TITLE
Change v8::Context::set_promise_hooks to require mutable parameter

### ISSUE THREAD

**Issue by bartlomieju** [denoland/rusty_v8#1180]
https://github.com/denoland/rusty_v8/pull/1178#discussion_r1093362563

**Comment by WingZer0o** [comment]
Just adding to this thread. Seems that just passing &mut HandleScope as a parameter is not FFI safe.

**Comment by bartlomieju** [comment]
@WingZer0o could you elaborate what you mean by that? We use `&mut HandleScope` extensively throughout the codebase.

**Comment by WingZer0o** [comment]
Ah yes, in the context of v8::Context::set_promise_hooks adding the extra parameter within the C++ binding and the Rust FFI. When running the test suite I was informed that using &mut HandleScope was not Rust FFI safe in a Rust warning. Which was quite strange to me because the test cases that required said extra parameter had a local function variable creating a new v8 scope that was typed as HandleScope.

I forgot to grab a snippet and post. I can repost my findings here sometime this weekend.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by WingZer0o** [comment]
When adding the sixth parameter in `context.rx` to v8__Context__SetPromiseHooks this is where our warning error occurs.

```rust
fn v8__Context__SetPromiseHooks(
    this: *const Context,
    init_hook: *const Function,
    before_hook: *const Function,
    after_hook: *const Function,
    resolve_hook: *const Function,
    scope: &mut HandleScope<'_, ()>
  );
```

```rust
warning: `extern` block uses type `scope::HandleScope<'_, ()>`, which is not FFI-safe
   --> src\context.rs:36:12
    |
36  |     scope: &mut HandleScope<'_, ()>
    |            ^^^^^^^^^^^^^^^^^^^^^^^^ not FFI-safe
    |
    = help: consider adding a `#[repr(C)]` or `#[repr(transparent)]` attribute to this struct
    = note: this struct has unspecified layout
note: the type is defined here
   --> src\scope.rs:148:1
    |
148 | pub struct HandleScope<'s, C = Context> {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    = note: `#[warn(improper_ctypes)]` on by default
```

Adding an `#[repr(C)]` attribute to the struct does not alleviate the warning. It will allow the test suite to pass by following the suggestion. 


Context.rs and Binding.cc where changed to the following respectively. 

```rust
fn v8__Context__SetPromiseHooks(
    this: *const Context,
    init_hook: *const Function,
    before_hook: *const Function,
    after_hook: *const Function,
    resolve_hook: *const Function,
    scope: &mut HandleScope<'_, ()>
  );

pub fn set_promise_hooks(
    &self,
    init_hook: Option<Local<Function>>,
    before_hook: Option<Local<Function>>,
    after_hook: Option<Local<Function>>,
    resolve_hook: Option<Local<Function>>,
    scope: &mut HandleScope<'_, ()>,
  ) {
    unsafe {
      v8__Context__SetPromiseHooks(
        self,
        init_hook.map_or_else(null, |v| &*v),
        before_hook.map_or_else(null, |v| &*v),
        after_hook.map_or_else(null, |v| &*v),
        resolve_hook.map_or_else(null, |v| &*v),
        scope
      )
    }
  }
```

```c++
void v8__Context__SetPromiseHooks(v8::Context& self,
                                  const v8::Function* init_hook,
                                  const v8::Function* before_hook,
                                  const v8::Function* after_hook,
                                  const v8::Function* resolve_hook,
                                  v8::HandleScope* scope) {
  ptr_to_local(&self)->SetPromiseHooks(
      ptr_to_local(init_hook), ptr_to_local(before_hook),
      ptr_to_local(after_hook), ptr_to_local(resolve_hook),
      ptr_to_local(scope));
}
```

**Comment by andreubotella** [comment]
In similar functions, the `&mut HandleScope` parameter is not passed to the C++ side, but is instead used with `scope.cast_local` to turn any `v8::Local<T>` into `*const T`.

**Comment by WingZer0o** [comment]
@andreubotella Thank you for the advice, where we dig down into `v8::Context::SetPromiseHooks` with this 6th parameter is where my knowledge of this project. Just figured I'd post what I had done so far.
