### ISSUE TITLE
Can't build for android on apple silicon or run the android example

### ISSUE THREAD

**Issue by neilsarkar** [denoland/rusty_v8#1193]
Following the trail of #970 and #860 I am attempting to make an android build from an m2 mac on the latest `main` branch (6dd892b111f6dd202bf41c4ea9051e6f3301c9ce).

```bash
$ docker login
Login Succeeded

$ cross --version
cross 0.2.5 (99b8069 2023-02-12)

$ cross build --target aarch64-linux-android
[cross] warning: got environment variable of "V8_FROM_SOURCE" which is not a valid environment variable name. the proper syntax is `passthrough = ["ENVVAR=value"]`
Unable to find image 'cross:aarch64-linux-android-0.2.1' locally
docker: Error response from daemon: pull access denied for cross, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```

Targeting android in the `cross` hello world example (https://github.com/cross-rs/rust-cpp-hello-word) is successful on the same system:

```bash
$ cross build --target aarch64-linux-android
info: downloading component 'rust-src'
info: installing component 'rust-src'
<jemalloc>: MADV_DONTNEED does not work (memset will be used instead)
<jemalloc>: (This is the expected behaviour if you are running under QEMU)
<jemalloc>: MADV_DONTNEED does not work (memset will be used instead)
<jemalloc>: (This is the expected behaviour if you are running under QEMU)
<jemalloc>: MADV_DONTNEED does not work (memset will be used instead)
<jemalloc>: (This is the expected behaviour if you are running under QEMU)
    Finished dev [unoptimized + debuginfo] target(s) in 1.60s
```

Is the android target still supported? Are there additional setup steps to build `rusty_v8` targeting android? 

Thank you!

(full terminal output)

<img width="1006" alt="rusty_v8_—_neilsarkar_Neils-MBP_—_-zsh_—_125×51" src="https://user-images.githubusercontent.com/83109/222265392-47de2aaa-3172-44c8-ba22-73cc1791eda0.png">

<img width="611" alt="rust-cpp-hello-word_—_neilsarkar_Neils-MBP_—_-zsh_—_125×51" src="https://user-images.githubusercontent.com/83109/222266742-7cb66355-5954-436a-9ce0-92efee4a444f.png">

**Comment by littledivy** [comment]
You need to build the rusty_v8 Docker image from the base cross image:

```
cd rusty_v8/

docker build \
    --build-arg CROSS_BASE_IMAGE=ghcr.io/cross-rs/aarch64-linux-android:0.2.5 \
    -t cross-rusty_v8:aarch64-linux-android .

V8_FROM_SOURCE=1 cross build --target aarch64-linux-android
```

Note: Cross compiling to aarch64 android is only tested on Linux so it might not work on arm macos.

**Comment by devsnek** [comment]
Someone figured out android here as well: https://github.com/denoland/rusty_v8/issues/1604
