### ISSUE TITLE
Run hello_world twice and it'll error with "Invalid global state" - same with other examples

### ISSUE THREAD

**Issue by matteliot** [denoland/rusty_v8#1325]
Hi, if you take one of the examples like hello_world and run the code twice, it'll give the error "Invalid global state". 

From what I can see, it's in the deno code so this doesn't appear to be a bug, but shouldn't the any state be eliminated after the 2 disposals?

If I call get_current_platform rather than the initializations I can get subsequent hello_worlds to run without error, but is there a way to force the runtime to reset back to the initial state? It doesn't seem like dispose and dispose_platform do anything- are there other calls that are needed?

Thanks

```
//call this twice and it'll give "thread 'main' panicked at 'Invalid global state'" 
fn bomb(){
    let platform = v8::new_default_platform(0, false).make_shared();
    v8::V8::initialize_platform(platform);
    v8::V8::initialize();

    unsafe {
        v8::V8::dispose();
    }
    v8::V8::dispose_platform();
}
```
asdasd

**Comment by lucacasonato** [comment]
You should not initialise the platform more than once. Platform must only be initalized exactly once per process.
