### ISSUE TITLE
error about `read_unaligned is not yet stable as a const fn`

### ISSUE THREAD

**Issue by Bylx666** [denoland/rusty_v8#1378]
I was building for the example, but got such errors.
```
error: `read_unaligned` is not yet stable as a const fn
   --> USER_CARGO\v8-0.82.0\src\fast_api.rs:248:14
    |
248 |     unsafe { ptr::read_unaligned(self.data.add(index)) }
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: could not compile `v8` (lib) due to previous error
```

rustc 1.70.0 (90c541806 2023-05-31)

v8 = "0.82.0"

**Comment by bartlomieju** [comment]
rusty_v8 requires Rust v1.71.0 to compile correctly. You can check it in https://github.com/denoland/rusty_v8/blob/main/rust-toolchain.toml.

**Comment by Bylx666** [comment]
Got alright with the rust nightly version, thanks for your patience.
