### ISSUE TITLE
Add target for x86_64-pc-windows-gnu

### ISSUE THREAD

**Issue by ahaoboy** [denoland/rusty_v8#1405]
Is it possible to support the build for x86_64-pc-windows-gnu?
```
cargo build --target x86_64-pc-windows-gnu
```
```
  Downloading https://github.com/denoland/rusty_v8/releases/download/v0.83.2/rusty_v8_release_x86_64-pc-windows-gnu.lib...
  HTTP Error 404: Not Found
  Python downloader failed, trying with curl.

```

**Comment by humphreylee** [comment]
Second that motion. I needed this to use [charming-rs.](https://github.com/yuankunzhang/charming) on Windows-gnu. Thanks.

**Comment by Krensi** [comment]
Hi! Maybe it would be possible to throw a more specific compiler error, which states that the target is not supported. Thanks for the great project! :-)

**Comment by Naxdy** [comment]
I second this. `x86_64-pc-windows-gnu` would make cross-compiling applications using V8 for Windows targets on Linux hosts _a lot_ easier, which is especially important for things like CI workflows.

**Comment by louis030195** [comment]
same, we use deno runtime in https://github.com/louis030195/screen-pipe

**Comment by Naxdy** [comment]
@devsnek Unfortunately this is not viable for cross-compilation, since setting up an environment to cross-compile V8 from Linux to Windows using the GNU toolchain is insanely complex (I gave up).

**Comment by devsnek** [comment]
Closing as I don't think there's anything actionable for us here.

**Comment by dillfrescott** [comment]
So is there a solution to this?

**Comment by tengfei2233** [comment]
Dear author, I need it too

**Comment by tengfei2233** [comment]
> Second that motion. I needed this to use [charming-rs.](https://github.com/yuankunzhang/charming) on Windows-gnu. Thanks.

I'm just like you, with using charming
