### ISSUE TITLE
How to get raw pointer from v8::String?

### ISSUE THREAD

**Issue by lazytiger** [denoland/rusty_v8#1580]
Hi, everyone. How to get a str or raw pointer from v8::String without copy?

**Comment by littledivy** [comment]
V8 strings are internally represented as Latin-1 or UTF-16 so it is not always possible to get a zero-copy Rust string view from it. 

You can get the raw pointer to the flattened string using [`v8::ValueView`](https://docs.rs/v8/latest/v8/struct.ValueView.html) or use `v8::String::to_rust_cow_lossy` https://github.com/denoland/rusty_v8/blob/1f5ebd9c4eb7fd79eabafa532fd8b3a3a6916a38/src/string.rs#L832-L836
