### ISSUE TITLE
How to implement a commonjs require in rusty_v8?

### ISSUE THREAD

**Issue by lazytiger** [denoland/rusty_v8#1602]
I am not sure if it is appropriate to ask questions here, if it is not, please forgive me.
I have tried Module, but it seems that it only works with import but not require. My project has a lot of commonjs dependencies. So I have to support it. Is there any example to do it? Thanks.

**Comment by marvinhagemeister** [comment]
CommonJS is not a standardized module system and thus not natively supported by V8. It's something the Node project added on top of it. The only standardized module system is ESM, which is supported by V8. If you want to add support for CommonJS, you'd need to build something on top of `rusty_v8`.

The way both Deno and Node do it, is by wrapping the module code with an IIFE function that passes some CommonJS special objects like `module`, `exports` and `require`. You'd also need some code to detect when a file should be treated as a CommonJS module and when it shouldn't.

**Comment by lazytiger** [comment]
Thanks for the explanation.
