### ISSUE TITLE
Example of returning a context?

### ISSUE THREAD

**Issue by erikschul** [denoland/rusty_v8#1630]
There are plenty of examples of creating a context:
```
    let isolate = &mut v8::Isolate::new(Default::default());
    let isolate_scope = &mut v8::HandleScope::new(isolate);
    let context = v8::Context::new(isolate_scope, Default::default());
    let context_scope = &mut v8::ContextScope::new(isolate_scope, context);
    let global = context.global(context_scope);
```

but want to do something like this:
```
    let mut contexts = vec![];
    for _ in 0..10 {
        let isolate = &mut v8::Isolate::new(Default::default());
        let isolate_scope = &mut v8::HandleScope::new(isolate);
        let context = v8::Context::new(isolate_scope, Default::default());
        let context_scope = &mut v8::ContextScope::new(isolate_scope, context);
        contexts.push(context_scope);
    }
```

The problem is that there is a mutable borrow. I can't return `context_scope` because the other variables are temporary.

For example this also isn't possible:
```
async fn start_async() {
    for _ in 0..10 {
        tokio::spawn(async {
            start_isolate().await;
        });
    }
}
async fn start_isolate() {
    let isolate = &mut v8::Isolate::new(Default::default());
    let isolate_scope = &mut v8::HandleScope::new(isolate);
    let context = v8::Context::new(isolate_scope, Default::default());
    let context_scope = &mut v8::ContextScope::new(isolate_scope, context);
    tokio::time::sleep(Duration::MAX).await;
}
```

because 
>future cannot be sent between threads safely [...], the trait `std::marker::Send` is not implemented for `std::ptr::NonNull<v8::Isolate>

Do you have an example of how to get around this?

**Comment by erikschul** [comment]
I noticed that you use this in `deno_core`
```
let mut isolate_scope = v8::HandleScope::new(unsafe { &mut *self.v8_isolate_ptr() });
```

**Comment by bartlomieju** [comment]
> but want to do something like this:

    let mut contexts = vec![];
    for _ in 0..10 {
        let isolate = &mut v8::Isolate::new(Default::default());
        let isolate_scope = &mut v8::HandleScope::new(isolate);
        let context = v8::Context::new(isolate_scope, Default::default());
        let context_scope = &mut v8::ContextScope::new(isolate_scope, context);
        contexts.push(context_scope);
    }

You can't really do that. You should create a short lived "scope" in the places where you need to and then let it drop so V8 can perform garbage collection.

> For example this also isn't possible:

async fn start_async() {
    for _ in 0..10 {
        tokio::spawn(async {
            start_isolate().await;
        });
    }
}
async fn start_isolate() {
    let isolate = &mut v8::Isolate::new(Default::default());
    let isolate_scope = &mut v8::HandleScope::new(isolate);
    let context = v8::Context::new(isolate_scope, Default::default());
    let context_scope = &mut v8::ContextScope::new(isolate_scope, context);
    tokio::time::sleep(Duration::MAX).await;
}

`rusty_v8` is meant to be used in a single-threaded Tokio runtime (current thread), so you can't use `tokio::spawn`. We have a utility crate to make it easier - https://docs.rs/deno_unsync/latest/deno_unsync/, use `deno_unsync::spawn()` instead.
