### ISSUE TITLE
Assert error: you should use v8::OwnedIsolate::create_blob before dropping an isolate.

### ISSUE THREAD

**Issue by linrongbin16** [denoland/rusty_v8#1643]
Hi, I'm trying to create snapshot with rusty_v8, version: "129.0.0".

Here's a very simple sample code: https://github.com/rsvim/rsvim/pull/192/files#diff-8fc5d2c29833795445cf47616cb37d30f06645102a74ceba0763395e0bffc36d.

But it fails with error message:

```text
  thread 'main' panicked at /Users/rlin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/v8-129.0.0/src/isolate.rs:1658:7:
  If isolate was created using v8::Isolate::snapshot_creator, you should use v8::OwnedIsolate::create_blob before dropping an isolate.
```

The error is thrown from the assertion: https://github.com/denoland/rusty_v8/blob/a076d039902a29ebcd8b7045386cb8b9405b42f1/src/isolate.rs#L1660.

I'm not sure why the isolate is been dropped before calling the API `create_blob`, would you please help me?

**Comment by linrongbin16** [comment]
Looks like it is related to the `Drop` trait, the `Isolate` is already been dropped when calling `create_blob` API, then rust will drop it again when the code runs in the end of the function.

**Comment by devsnek** [comment]
deno_core only uses `ManuallyDrop` to control the order in which things within the same struct are dropped. You shouldn't need it at all. I would suggest removing all the unsafe and raw pointer stuff you're doing and seeing if its still an issue after that.

**Comment by linrongbin16** [comment]
hi @devsnek , would you please take a look at below PR:

- [build.rs](https://github.com/rsvim/rsvim/pull/196/files#diff-8fc5d2c29833795445cf47616cb37d30f06645102a74ceba0763395e0bffc36d)
- [JsRuntime::new_for_snapshot()](https://github.com/rsvim/rsvim/pull/196/files#diff-6f613c1156ae6d9cbafc710c7ce50910b61bf263c598fd8e12232cec85b072beR311)

**Comment by linrongbin16** [comment]
When looking into the early version of deno core's source code, I found this:

https://github.com/denoland/deno/blob/d0efd040c79021958a1e83caa56572c0401ca1f2/core/runtime.rs#L93 

The `JsRuntime` looks similar to what I've got here, but it contains the `Option<v8::OwnedIsolate>`, instead of `v8::OwnedIsolate` directly. It maybe the answer to our issue here.
