### ISSUE TITLE
Can't expose closure to JS since its not a UnitValue

### ISSUE THREAD

**Issue by shyguy1412** [denoland/rusty_v8#1654]
I want dynamically create closures at runtime then expose them to JS. I have the following function to do so 

```rs
pub fn expose_function(
    &self,
    identifier: &str,
    callback: fn(args: Vec<WeakType>) -> WeakType,
) -> Result<(), Error> {
    let env = match &self.environment {
        Some(v) => v,
        None => return Err(Error::InvalidEnvironment),
    };

    let scope = env.context_scope()?;
    let identifier = identifier.as_local(scope)?;

    let function = |scope: &mut v8::HandleScope<'_>,
                    args: v8::FunctionCallbackArguments,
                    mut retval: v8::ReturnValue| {
        let mut weak: Vec<WeakType> = vec![];
        for i in 0..args.length() {
            godot_print!("PARSING ARG {}", i);
            let current_arg = args.get(i);
            // let value = current_arg.to_rust_string_lossy(scope);
            weak.push(current_arg.as_weak_type(scope));
        }

        let result = callback(weak);
        retval.set(result.as_local(scope));
    };

    let function = v8::FunctionTemplate::new(scope, function)
        .get_function(scope)
        .unwrap();

    scope
        .get_current_context()
        .global(scope)
        .set(scope, identifier.into(), function.into());

    return Ok(());
}
```

The issue I am having is that a closure that captures outside values isn't a UnitValue. 
Specifically this line is throwing the error <https://github.com/denoland/rusty_v8/blob/428b1765d2a55373be977af40252264813338779/src/support.rs#L590>

Is there any way around this? I'm not very experienced with rust so I am hoping I am just missing something here.

**Comment by devsnek** [comment]
You are not missing something, this is unsupported. You would need to use something like https://docs.rs/v8/latest/v8/struct.FunctionBuilder.html#method.data to associate data with a function.

**Comment by shyguy1412** [comment]
Thx for the quick answer! How would I go about accessing the associated data inside the function?

**Comment by shyguy1412** [comment]
Figured it out, I can get it via <https://docs.rs/rusty_v8/latest/rusty_v8/struct.FunctionCallbackArguments.html#method.data>.

Thx for pointing me in the right direction, I can work with this!
