### ISSUE TITLE
Implicitly enter Isolate in v8::error()

### ISSUE THREAD

**Issue by bartlomieju** [denoland/rusty_v8#190]
Exceptions is one of few APIs that still require to enter isolate before calling constructor method (as they internally rely on `Isolate::GetCurrent()`.

Since we already have `scope` argument in each of the methods used to create different errors I think we might want to implicitly enter/exit isolate when creating errors:

```rust
// now
pub fn error<'sc>(
  scope: &mut impl ToLocal<'sc>,
  mut message: Local<String>,
) -> Local<'sc, Value> {
  unsafe { scope.to_local(v8__Exception__Error(&mut *message)) }.unwrap()
}

// proposed change
pub fn error<'sc>(
  scope: &mut impl ToLocal<'sc>,
  mut message: Local<String>,
) -> Local<'sc, Value> {
  let isolate = scope.isolate();
  isolate.enter();
  let e = unsafe { scope.to_local(v8__Exception__Error(&mut *message)) }.unwrap();
  isolate.exit();
  e
}
```

CC @ry @piscisaureus

**Comment by piscisaureus** [comment]
Yes! That's exactly what I had in mind.
