### ISSUE TITLE
APIs required to implement inspector

### ISSUE THREAD

**Issue by bartlomieju** [denoland/rusty_v8#205]
- `v8_inspector::V8Inspector`
  - `create`
  - `connect`
  - `StringView`
- `v8_inspector::ContextInfo`
  - `new`
- `v8_inspector::InspectorSession`
  - `dispatchProtocolMessage`
  - `schedulePauseOnNextStatement`
- API to get Rust `String` out of `StringView` if it is two-byte string (`!string_view.is_8_bit()`)

CC @piscisaureus

**Comment by piscisaureus** [comment]
> * API to get Rust `String` out of `StringView` if it is two-byte string (`!string_view.is_8_bit()`)

1. Not sure you need it at all. I think all you need to do is forward the message between the client and server.
2. If you do need it, this would do the trick: https://doc.rust-lang.org/std/string/struct.String.html#method.from_utf16.
3. Also, an 8bit string_view is *not* encoded as UTF8 but as Latin-1. Converting an 8bit StringView is probably more involved than converting a 16bit string.

**Comment by bartlomieju** [comment]
> Not sure you need it at all. I think all you need to do is forward the message between the client and server.

I'm prototyping now on types, you might be right, I'll get back on that

> If you do need it, this would do the trick: https://doc.rust-lang.org/std/string/struct.String.html#method.from_utf16.

:+1:

> Also, an 8bit string_view is not encoded as UTF8 but as Latin-1. Converting an 8bit StringView is probably more involved than converting a 16bit string.

You are right, looks like previous implementation did convert to `Utf8Value` before actually encoding into string. 
```cpp
void InspectorFrontend::Send(const v8_inspector::StringView& string) {
  v8::HandleScope handle_scope(isolate_);
  int length = static_cast<int>(string.length());
  DCHECK_LT(length, v8::String::kMaxLength);
  Local<String> message =
      (string.is8Bit()
           ? v8::String::NewFromOneByte(
                 isolate_,
                 reinterpret_cast<const uint8_t*>(string.characters8()),
                 v8::NewStringType::kNormal, length)
           : v8::String::NewFromTwoByte(
                 isolate_,
                 reinterpret_cast<const uint16_t*>(string.characters16()),
                 v8::NewStringType::kNormal, length))
          .ToLocalChecked();

  String::Utf8Value utf8(isolate_, message);
  std::string str(*utf8);

  char* cstr = &str[0u];

  deno_->inspector_message_cb_(deno_->hack_, cstr);
}
```

**Comment by bartlomieju** [comment]
> > * API to get Rust `String` out of `StringView` if it is two-byte string (`!string_view.is_8_bit()`)
> 
> 1. Not sure you need it at all. I think all you need to do is forward the message between the client and server.
> 2. If you do need it, this would do the trick: https://doc.rust-lang.org/std/string/struct.String.html#method.from_utf16.
> 3. Also, an 8bit string_view is _not_ encoded as UTF8 but as Latin-1. Converting an 8bit StringView is probably more involved than converting a 16bit string.

Okay, checked, we need that conversion because those messages are pushed/pulled via WS socket which requires `String` type for messages.

**Comment by kitsonk** [comment]
In order to solve denoland/deno#106 we would also need the following APIs exposed:

- [`Profiler.startPreciseCoverage`](https://chromedevtools.github.io/devtools-protocol/tot/Profiler#method-startPreciseCoverage)
- [`Profiler.takePreciseCoverage`](https://chromedevtools.github.io/devtools-protocol/tot/Profiler#method-takePreciseCoverage)
- [`Profiler.stopPreciseCoverage`](https://chromedevtools.github.io/devtools-protocol/tot/Profiler#method-stopPreciseCoverage)

A [V8 blog post](https://v8.dev/blog/javascript-code-coverage) describes the process in detail.

**Comment by piscisaureus** [comment]
Closing this as the currently bound APIs were sufficient to implement the inspector in Deno.

If other APIs mentioned in this thread (e.g. Profiler.*) are still missing and still needed, feel free to open a separate issue (or PR).
