### ISSUE TITLE
inspector: human-readable StringBuffer, StringView

### ISSUE THREAD

**Issue by bnoordhuis** [denoland/rusty_v8#233]
For debugging the wire protocol. Just adding `#[derive(Debug)]` produces:

    UniquePtr(Some(StringBuffer { _cxx_vtable: CxxVTable(0x55d8a19e34b0) }))

Not super useful, I daresay.

**Comment by ry** [comment]
Agree - we should try to remove these `derive(Debug)` things a much as possible - it's a lot of extra code for little benefit. For example, it doesn't seem useful to have it on `UniquePtr`. It probably makes sense to have a custom `impl Debug` for StringBuffer tho.
