### ISSUE TITLE
support arm platforms

### ISSUE THREAD

**Issue by afinch7** [denoland/rusty_v8#265]
I've done a little research on this. It looks like cross compiling to arm64 works fine, but it requires some  setup and small changes:

* Sysroot usage is required (need to remove `use_sysroot = false` from gn options when compiling to arm)
* `target_cpu` needs to be set correctly (and maybe `v8_target_cpu` not sure yet)

Other than these and installing the correct toolchain it's not to hard to compile for arm64 successfully. I would like to get a build with tests running in CI for at least arm64 and maybe other arm platforms if possible.

**Comment by ry** [comment]
I would also like to get arm64 build settled. Looks like Github Action has support for arm https://github.blog/changelog/2019-12-03-github-actions-self-hosted-runners-on-arm-architectures/

**Comment by joshgillies** [comment]
Any chance of getting armv7 builds off the back of the work done in #266?

**Comment by piscisaureus** [comment]
Arm64 has been supported for a while now.

I'm not aware of anyone working on armv7 support, and we (as in "the maintainers") are not going to in the foreseeable future. 

However if someone submits PR I'd be willing to work with them to get it landed.
