### ISSUE TITLE
Broken binary on 64-bit Windows

### ISSUE THREAD

**Issue by seishun** [denoland/rusty_v8#269]
I might be doing something wrong, but it seems binding.cc gets built for x64, while the Rust code gets built for x86. This causes linker errors when this crate is used: https://github.com/denoland/deno/issues/3716

Steps:
1. Clone the repo and run `cargo build -vv`.
2. Open target/debug/librusty_v8.rlib in 7-Zip, extract rusty_v8/binding.obj and one of the Rust .o files, compare their `dumpbin /headers` outputs.

Expected: same "machine" values.

Actual: Rust object files have `14C machine (x86)`, binding.obj has `8664 machine (x64)`.

**Comment by piscisaureus** [comment]
What does the output of `rustup show` look like?

**Comment by seishun** [comment]
```
Default host: i686-pc-windows-msvc
rustup home:  C:\Users\Nikolai\.rustup

stable-i686-pc-windows-msvc (default)
rustc 1.41.0 (5e1a79984 2020-01-27)
```

**Comment by piscisaureus** [comment]
We don't support building Deno for 32-bit x86 targets, and I'm not sure we ever will.
So i'd suggest to install the 64-bit rust toolchain. I'm not really sure how to do this, so I'd suggest:

1. Uninstall rust / rustup.
2. Install rust using rustup-init x64 from https://win.rustup.rs/x86_64

**Comment by seishun** [comment]
Should that be mentioned in the docs here (and in deno)? Currently, installing Rust from https://www.rust-lang.org/tools/install will get you a 32-bit toolchain by default (although it seems it's going to change, see https://github.com/rust-lang/rustup/pull/2186 and https://github.com/rust-lang/www.rust-lang.org/pull/1004).

**Comment by ry** [comment]
@seishun yes some comments in the manual would be helpful.
