### ISSUE TITLE
support taking HeapSnapshots

### ISSUE THREAD

**Issue by bartlomieju** [denoland/rusty_v8#298]
To figure out performance problems with [`deno_tcp.ts`](https://github.com/denoland/deno/blob/master/tools/deno_tcp.ts) (which are GC problems) we need to inspect what's going on on V8 heap.

This is partially related to #205 but can be implemented independently and used without full inspector support.

There's [`node-heapdump`](https://github.com/bnoordhuis/node-heapdump) which implements that functionality fo node. 

Grepping through [`node-heapdump/heapdump.cc`](https://github.com/bnoordhuis/node-heapdump/blob/master/src/heapdump.cc) it seems that APIs that we should port are:
- `Isolate::GetHeapProfiler`
- `HeapProfiler::TakeHeapSnapshot `
- `HeapSnapshot::Serialize`

CC @bnoordhuis for expert advice on the subject

**Comment by bnoordhuis** [comment]
I can write bindings, that shouldn't be too complicated, but the question is where to send the data chunks to.

node-heapdump writes them out to disk to avoid having to round-trip through JS land because it's easy to hit out-of-memory conditions that way.

**Comment by bartlomieju** [comment]
> I can write bindings, that shouldn't be too complicated, but the question is where to send the data chunks to.
> 
> node-heapdump writes them out to disk to avoid having to round-trip through JS land because it's easy to hit out-of-memory conditions that way.

That'd be awesome thanks! My direct need for this feature is to take some dumps of `deno_tcp.ts` heap; I haven't put much thought how to call that API, but I guess I could just directly bind it to global object (`globalThis.takeHeapSnapshot()`) and write out to disk - but that would be done in `deno_core`

**Comment by bnoordhuis** [comment]
I'll open a PR here tomorrow.

**Comment by bartlomieju** [comment]
Done in #302
