### ISSUE TITLE
Support for Externals

### ISSUE THREAD

**Issue by JohnDoneth** [denoland/rusty_v8#304]
Currently it doesn't appear that we can use `v8::External`'s from Rust.

I would like to bind a Rust struct to the VM and the way I would do that in C++ would be to store the pointer using `obj->SetInternalField(0, External::New(myobjectpointer));` and then back again.

It would be awesome if we could `Box` up a struct and put it in an `External` by it's pointer. I'm not sure if there's a way to do that in the reverse without using unsafe but I would be happy with that as I know what types I am using.

The last thing to keep in mind is that a way to provide a finalizer to drop the box and free the memory should be possible in order to avoid holding onto memory forever. From a quick search it looks like `PersistentBase::SetWeak` is used to cleanup memory for bound C++ classes in Node.js. I'm not sure how this would translate to Rust.

**Comment by piscisaureus** [comment]
Support for 'External' was added in https://github.com/denoland/rusty_v8/commit/82d02870286ebb9ae75639d775d0af6b97eca00.

Support for weak handles / finalizers is yet TBD, which I consider a separate issue.
