### ISSUE TITLE
gn gen failure on macOS

### ISSUE THREAD

**Issue by chrmoritz** [denoland/rusty_v8#328]
I'm not able to build versions after the V8 upgrade to 8.2.308 (https://github.com/denoland/rusty_v8/commit/8a3c19ece4cc0ed1a7b116ce5005864ca3472fee) from source on macOS, because of a failure in the `gn gen` command:

```
[rusty_v8 0.3.9] Downloading https://github.com/denoland/ninja_gn_binaries/archive/20200313.tar.gz... Done.
[rusty_v8 0.3.9] using Chromiums clang
[rusty_v8 0.3.9] clang_base_path /Users/chrmoritz/Documents/git/rusty_v8/target/debug/clang
[rusty_v8 0.3.9] Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Mac/clang-n344329-9284abd0-5.tgz .......... Done.
[rusty_v8 0.3.9] cargo:warning=Not using sccache
[rusty_v8 0.3.9] cargo:rustc-env=GN_OUT_DIR=/Users/chrmoritz/Documents/git/rusty_v8/target/debug/gn_out
[rusty_v8 0.3.9] running: "/Users/chrmoritz/Documents/git/rusty_v8/target/debug/ninja_gn_binaries-20200313/mac/ninja" "-C" "/Users/chrmoritz/Documents/git/rusty_v8/target/debug/gn_out" "rusty_v8"
[rusty_v8 0.3.9] ninja: Entering directory `/Users/chrmoritz/Documents/git/rusty_v8/target/debug/gn_out'
[rusty_v8 0.3.9] ninja: error: rebuilding 'build.ninja': subcommand failed
[rusty_v8 0.3.9] [1/1] Regenerating ninja files
[rusty_v8 0.3.9] FAILED: build.ninja 
[rusty_v8 0.3.9] ../build/rusty_v8-55982c004f00657d/out/gn_ninja_binaries/mac/gn --root=../../.. -q gen .
[rusty_v8 0.3.9] ERROR at //build/toolchain/mac/BUILD.gn:236:17: Unknown substitution pattern
[rusty_v8 0.3.9]       command = "$cc -MMD -MF $depfile {{defines}} {{include_dirs}} {{framework_dirs}} {{cflags}} {{cflags_objc}} -c {{source}} -o {{output}}"
[rusty_v8 0.3.9]                 ^-----------------------------------------------------------------------------------------------------------------------------
[rusty_v8 0.3.9] Found a {{ at offset 106 and did not find a known substitution following it.
[rusty_v8 0.3.9] See //build/toolchain/mac/BUILD.gn:484:1: whence it was called.
[rusty_v8 0.3.9] mac_toolchain("clang_arm") {
[rusty_v8 0.3.9] ^---------------------------
[rusty_v8 0.3.9] See //v8/gni/v8.gni:266:3: which caused the file to be included.
[rusty_v8 0.3.9]   static_library(target_name) {
[rusty_v8 0.3.9]   ^----------------------------
[rusty_v8 0.3.9] thread 'main' panicked at '
[rusty_v8 0.3.9] command did not execute successfully, got: exit code: 1
[rusty_v8 0.3.9] 
[rusty_v8 0.3.9] build script failed, must exit now', /Users/chrmoritz/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo_gn-0.0.15/src/lib.rs:203:3
[rusty_v8 0.3.9] note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
error: failed to run custom build command for `rusty_v8 v0.3.9 (/Users/chrmoritz/Documents/git/rusty_v8)`
```

Relevant chromium/build commit, which has introduced the `{{framework_dirs}}` at offset 70, which it's complaining about: https://github.com/denoland/chromium_build/commit/62dad5c5423c78f7ea2cf02cc535dcffe52a0734#diff-0448a2a05f9be285643f46f44cc31272.

This also blocks us in Homebrew from upgrading `deno` past 0.36.0 (Refs: https://github.com/Homebrew/homebrew-core/pull/52095)

**Comment by IllusionPerdu** [comment]
do you use rust 1.4.2 ? if not, try to update rust !

**Comment by chrmoritz** [comment]
This is with rust 1.4.2. Also a syntax error in `BUILD.gn` files during the `gn gen` run should be completely unrelated to rust though.

**Comment by chenrui333** [comment]
> do you use rust 1.4.2 ? if not, try to update rust !

I assume that is Rust 1.42.0.

Anyway, it seems working fine now (with Rust 1.42.0).

**Comment by chrmoritz** [comment]
@chenrui333 but only because you're using the precompiled `rust_v8` binary. Building it from source by setting `V8_FROM_SOURCE=1` still fails.

**Comment by ry** [comment]
@chrmoritz what version of gn are you using? We updated the binary during the upgrade.

**Comment by chrmoritz** [comment]
@ry: The error from above is from cloning this repository and using it's default precompiled binaries. But I keep that in mind, that we might have to update `gn` too in the homebrew formula.

**Comment by chrmoritz** [comment]
@ry: Thx, updating `gn` fixes the issue.

I did the test from above in an old checkout with the old binaries still laying around and it didn't update them. Also we need to update `gn` in homebrew.

**Comment by chrmoritz** [comment]
@ry FYI: The last remaining issue with the v8 upgrade in Homebrew is, that https://github.com/denoland/chromium_build/commit/8a57822b3fdbf7164ccce5703691de28b91663d2 breaks support for High Sierra, because `libtool -D` isn't available there.

**Comment by ry** [comment]
I wonder if setting “enable_dsyms = false” will help?

I think this might be caused by https://github.com/denoland/rusty_v8/commit/c9b820894ed521578fefc53fd74e0703026a9dfd

**Comment by chrmoritz** [comment]
It comes from the V8 upgrade to 8.2 and more specific this commit: denoland/chromium_build@8a57822. Google has just decided to drop supporting building V8 on High Sierra (it will still run on it however). The `libtool` shipped with HighSierra (CLT or the max possible XCode 10.1) isn't new enough and doesn't support the `-D` flag, only the `ZERO_AR_DATE` env var from which they've moved in said commit.

I don't think we can do anything about it except dropping support for building on High Sierra too (or reverting said commit of course).

**Comment by ry** [comment]
@chrmoritz I’d be happy to revert that commit in our local fork if it helps.

**Comment by chrmoritz** [comment]
@ry This would help Homebrew to continue supporting High Sierra for `deno`, because the binary bottles are build on the macOS version they should run on and currently it's not possible to build it on High Sierra because of a too old `libtool`.
