### ISSUE TITLE
rusty_v8 not compiling when cargo build -vv

### ISSUE THREAD

**Issue by Drunpy** [denoland/rusty_v8#346]
Tried to compile deno with _cargo build -vv_ and got this.
```
error[E0308]: mismatched types
   --> /home/lorran/.cargo/registry/src/github.com-1ecc6299db9ec823/rusty_v8-0.3.10/src/try_catch.rs:134:5
    |
134 | /     unsafe {
135 | |       let msg = Local::from_raw(v8__TryCatch__Message(&self.0));
136 | |     }
    | |_____^ expected enum `std::option::Option`, found `()`
    |
    = note:   expected enum `std::option::Option<local::Local<'tc, data::Message>>`
            found unit type `()`
```
cargo 1.42.0 (86334295e 2020-01-31)
rustc 1.42.0 (b8cedc004 2020-03-09)

**Comment by piscisaureus** [comment]
That's odd. The actual file when v0.3.10 was released looked like this: https://github.com/denoland/rusty_v8/blob/v0.3.10/src/try_catch.rs#L134 -- which is correct.

I tried `cargo fetch`, and the file that it downloaded also had the right content:

![image](https://user-images.githubusercontent.com/218257/78940978-0e8dcf80-7ab7-11ea-8dec-4ab556441a95.png)

Long story short, I think your device got struck by a cosmic ~ray~semicolon, or there's a creepy clown editing your files when you sleep at night.
