### ISSUE TITLE
Get link errors when upgrading rusty_v8

### ISSUE THREAD

**Issue by ry** [denoland/rusty_v8#377]
When I use rusty_v8 as a dependency and it gets upgrade, it doesn't seem to use the new `librusty_v8.a` because I get link errors if the ABI has changed.

For example, a recent upgrade of deno_core resulted in this error
```
  = note: Undefined symbols for architecture x86_64:
            "_v8__Isolate__CreateParams__SIZEOF", referenced from:
                _$LT$rusty_v8..isolate_create_params..raw..CreateParams$u20$as$u20$core..default..Default$GT$::default::h57323b37433ca0e9 in librusty_v8-2afbb5eb4a6bf179.rlib(rusty_v8-2afbb5eb4a6bf179.rusty_v8.8w61v7cb-cgu.3.rcgu.o)
            "_v8__Isolate__CreateParams__CONSTRUCT", referenced from:
                _$LT$rusty_v8..isolate_create_params..raw..CreateParams$u20$as$u20$core..default..Default$GT$::default::h57323b37433ca0e9 in librusty_v8-2afbb5eb4a6bf179.rlib(rusty_v8-2afbb5eb4a6bf179.rusty_v8.8w61v7cb-cgu.3.rcgu.o)
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by piscisaureus** [comment]
That's correct, there's currently no logic in build.rs to update librusty_v8.a -- if it's there, it'll be used.

**Comment by waterbang** [comment]
I also get this error when trying to build `librusty_v8_release_aarch64-linux-android.a`, is there a way to avoid this error? Because I'm not familiar with `V8`. So it's not clear how to write `ABI`

**Comment by devsnek** [comment]
Downloads save using the package version in the filename now, so I don't think this is an issue anymore.
