### ISSUE TITLE
[Question] How to enable the output from the console API

### ISSUE THREAD

**Issue by tglman** [denoland/rusty_v8#392]
Hi,
I've been integrating this library in a small project, for run simple scripts, all works fine so far, but the `console.log(....)` do not print anything, I've been digging in the code of this and of Deno to figure out how to enable that, the only API I found is `V8InspectorClientImpl::console_api_message`, but do not seems to me the correct entry point, could you advise me on how to enable that, or point me to the code of Deno that actually implement the `console.log`.

Thank you in advance
Regards

**Comment by HotQ** [comment]
https://github.com/denoland/rusty_v8/pull/252/files?file-filters%5B%5D=.rs#diff-dfadab232a4207c16b3c3b582f3415c3R2354
