### ISSUE TITLE
Replace `download_file.py` with rust & curl

### ISSUE THREAD

**Issue by 06kellyjac** [denoland/rusty_v8#403]
Related to #373 

The curl option is there if people want to use the static binary but not use python.
This is great. I also saw the comment about moving to curl only so this is slightly related.

The python script will check locally for the lib file and skip downloading, it'd be nice if this check was done first in rust, then there's be no need for python or curl in some cases.

~I can replace the python script completely if you'd like but I think I'll save that for another issue~
Actually it's pretty small so I'm happy to replace it with just curl

**Comment by devsnek** [comment]
the build script now attempts to use curl if python fails.
