### ISSUE TITLE
Question: Is it possible to call Rust functions?

### ISSUE THREAD

**Issue by cemremengu** [denoland/rusty_v8#404]
As it says on the tin, is it possible to call rust functions from javascript code? I am planning to use `rusty_v8` as an embedded javascript interpreter library. I browsed the docs and code a bit but I lack knowledge in Rust so I still wasnt sure and apologies for bothering you for this. I am looking for something like this (examples are from golang):

```
vm.Set("sayHello", func(call otto.FunctionCall) otto.Value {
    fmt.Printf("Hello, %s.\n", call.Argument(0).String())
    return otto.Value{}
})

vm.Run(`
    sayHello("Xyzzy");
`)
```

**Comment by bartlomieju** [comment]
@cemremengu you might want to take a look at [`deno_core`](https://github.com/denoland/deno/tree/master/core) - it's a bit higher level crate that provides mechanism to communicate from JS to Rust. Take a look at HTTP bench example: https://github.com/denoland/deno/blob/master/core/examples/http_bench.js#L63-L89

**Comment by apiel** [comment]
To call a function from JS, you have to create a `FunctionTemplate`.

```rs
    ...
    let object_templ = v8::ObjectTemplate::new(scope);
    let function_templ = v8::FunctionTemplate::new(scope, fortytwo_callback);
    let name = v8::String::new(scope, "yo").unwrap();
    object_templ.set(name.into(), function_templ.into());
    let context = v8::Context::new_from_template(scope, object_templ);
    let mut cs = v8::ContextScope::new(scope, context);
    let scope = cs.enter();
   ...
```
```rs
fn fortytwo_callback(
    scope: v8::FunctionCallbackScope,
    _: v8::FunctionCallbackArguments,
    mut rv: v8::ReturnValue,
) {
    rv.set(v8::Integer::new(scope, 42).into());
}
```
You can find a full example in the unit test of rusty_rs https://github.com/denoland/rusty_v8/blob/master/tests/test_api.rs#L2827

You can also have a look at this app I am building to learn rusty_v8, it might be more simple to understand than deno: https://github.com/apiel/v8io/blob/master/core_functions/mod.rs

**Comment by 8bitkitkat** [comment]
@bartlomieju could you point to the specific rust code that exposes a rust function to js, I can't understand any of the example, none of it is commented.

**Comment by bartlomieju** [comment]
@8bitkitkat take a look at Rust side of the example: https://github.com/denoland/deno/blob/ccd0d0eb79db6ad33095ca06e9d491a27379b87a/core/examples/http_bench.rs#L184-L195

Here's a `close` op that is registered with the isolate and later can be used from JS. If you need more info drop by the Discord channel: https://discord.com/channels/684898665143206084/684898665151594506

**Comment by piscisaureus** [comment]
It is also possible to create a `v8::Function` directly, without creating a template. The `v8::Function` object can be called from JavaScript if you e.g. assign it to the global object. [Here](https://github.com/denoland/rusty_v8/blob/fa8f636397822ba7dbb823d25dc637bf77f8b1ce/tests/test_api.rs#L1091-L1101) is an example (note that the rust function that gets called in this example is a closure).
