### ISSUE TITLE
Is it possible for rusty_v8 to rely on an external libv8(shared library)?

### ISSUE THREAD

**Issue by HotQ** [denoland/rusty_v8#411]
I'm really on rusty_v8 and have built my own js runtime with rusty_v8. But this crate is rely on v8 as a static lib (which is very big) so that my app swelled by more than 20 megabytes. 

I want to reuse `libv8.dylib` already in my app, so is there any way to build `binding.cc` as static lib and link a shared `libv8`?

Help wanted, thx!

**Comment by bnoordhuis** [comment]
There's no technical reason rusty_v8 couldn't do that but it'll be unreliable unless your libv8 is the exact same version as rusty_v8's (up to and including the patch version.)

'Unreliable' should be read as prone to crash, behave erratically, break on upgrades, etc. I wouldn't recommend it. You're probably better off using rusty_v8's copy of V8.
