### ISSUE TITLE
[Question] Is it a global scope at the script run?

### ISSUE THREAD

**Issue by 18kb** [denoland/rusty_v8#437]
```
let source = v8::String::new(scope,"let a=1;").unwrap();
v8::Script::compile(scope, source, None).unwrap().run(scope);
{
    let scope = &mut v8::HandleScope::new(scope);
    let source = v8::String::new(scope,"let a=2;").unwrap();    //Uncaught SyntaxError: Identifier 'a' has already been declared
    v8::Script::compile(scope, source, None).unwrap().run(scope);
}
```

`let scope = &mut v8::HandleScope::new(scope);`

With this, the scope is nested, and I think that it is a script run in that scope. Is it like this?

**Comment by bartlomieju** [comment]
`HandleScope` is not a scope like `window` or lexical scope created by a block:
```
let a = 1;
{
  let a = 2;
}
```
It's a V8 API construct used to track different JS objects that informs the engine when the object can be garbage collected. 

I think you're looking for `v8::Context`, take a look at this example: https://github.com/denoland/deno/blob/684eddcc6bf0c1446c9aba0cdf001c661c19ab24/core/bindings.rs#L112-L113

**Comment by 18kb** [comment]
I understand that it is for garbage collectors.
Thank you for the example. I'll try reading it.
