### ISSUE TITLE
Running on Raspberry pi

### ISSUE THREAD

**Issue by Nathan1852** [denoland/rusty_v8#456]
Are there any plans to make this crate work on raspberry pies/Raspbian?

It currently doesn't seem to work

**Comment by lucacasonato** [comment]
rusty_v8 does have aarch64 support on Linux. Make sure you are actually compiling for aarch64.

The issue might be that you are using Raspbian though. It only has support for aarch32 at the moment, so you can not execute aarch64 binaries. You can try the Raspbian 64 Bit beta though - that might work.

@piscisaureus Are there any plans to support aarch32 in the future?

**Comment by Nathan1852** [comment]
Ah, that may be my problem. I'll look into the aarch64 beta then

**Comment by piscisaureus** [comment]
> @piscisaureus Are there any plans to support aarch32 in the future?

_I_ do not have any plans to work on this and I'm not aware of other people doing that. 
Unfortunately I can't tell you whether or not *any* plans exists 😛.

However a PR that makes arm32 builds work would be welcome.
