### ISSUE TITLE
Where is v8::Isolate::GetCurrent?

### ISSUE THREAD

**Issue by Icemic** [denoland/rusty_v8#469]
Hi, I am porting a program on v8 in C++ to Rust, and finding rusty_v8.

In C++, I always write `auto isolate = v8::Isolate::GetCurrent();` to get current isolate somewhere (for example, in the callback of libuv). But I cannot find this method in rusty_v8 as rusty_v8::Isolate only has `new()` and `create_params()`.

https://chromium.googlesource.com/v8/v8.git/+/refs/heads/8.7.75/include/v8.h#8592

I tried adding binding by myself: 

```rust
extern "C" {
    fn v8__Isolate__GetCurrent() -> *mut Isolate;
}
```

Only to get a linking error telling me there's no Isolate::GetCurrent in rusty_v8.lib

So my question are:
1. Does rusty_v8 use a modified version of v8 which removes GetCurrent method?
2. How to get current isolate in rusty_v8?

Thanks.

**Comment by bnoordhuis** [comment]
> 1. Does rusty_v8 use a modified version of v8 which removes GetCurrent method?

No. :-)

> 2. How to get current isolate in rusty_v8?

You also need to update `src/binding.cc`.

That said, I don't think `Isolate::get_current()` would play nicely with Rust's ownership and aliasing rules.

Does `isolate.thread_safe_handle()` work for your use case? It returns an `IsolateHandle` that's `Clone`, `Send` and `Sync`, in order that you can (safely!) pass it around.

**Comment by Icemic** [comment]
> > 1. Does rusty_v8 use a modified version of v8 which removes GetCurrent method?
> 
> No. :-)
> 
> > 1. How to get current isolate in rusty_v8?
> 
> You also need to update `src/binding.cc`.
> 
> That said, I don't think `Isolate::get_current()` would play nicely with Rust's ownership and aliasing rules.
> 
> Does `isolate.thread_safe_handle()` work for your use case? It returns an `IsolateHandle` that's `Clone`, `Send` and `Sync`, in order that you can (safely!) pass it around.

I don't think so too : P  but seems no choice before.

And I did notice IsolateHandle, but how to get a valid isolate via IsolateHandle? In document, it says a it's to terminal a execution instead of malloc a new handle scope. IsolateHandle only has one `terminate_execution` method.

btw, my case:

```cpp
  // it's a libuv callback with only the timer handle of libuv as parameter
  void _timer_callback(uv_timer_t* timer) {
    // get a isolate
    auto isolate = v8::Isolate::GetCurrent();

    // TimerInfo is a struct storing Global<Function>
    auto timerInfo = callbackMap[timer];

    // new a handle scope
    v8::HandleScope scope(isolate);

    // restore callback to local
    v8::Local<v8::Function> callback = v8::Local<v8::Function>::New(isolate, *(timerInfo->callbackFunc));

    // run callback
    // ...
  }
```

**Comment by bartlomieju** [comment]
@Icemic `rusty_v8`'s `Isolate` are `!Send` which means they are pinned to specific thread and cannot be moved between threads. This is by design as we found out it's very problematic to move isolates between threads (eg. there's no `Locker` too). It means you need to store the handle to the isolate yourself. Maybe @piscisaureus can provide more rationale on the decision.

**Comment by Icemic** [comment]
@bnoordhuis In fact, libuv runs in single thread as well as tokio (features=["rt-core"]), however rust don't know it, though. 

The problem is *once I lost the isolate (not or cannot pass it to the next fn), I have no way to find it back*. No matter it's in which thread or function.

**Comment by bnoordhuis** [comment]
If your program is single-threaded, I'd probably just stick the isolate in a thread-local `RefCell`. I expect you have to use `std::mem::transmute(&mut isolate)` to pacify the borrow checker, though.

**Comment by Icemic** [comment]
> If your program is single-threaded, I'd probably just stick the isolate in a thread-local `RefCell`. I expect you have to use `std::mem::transmute(&mut isolate)` to pacify the borrow checker, though (edit: or `Box` it up.)

Sorry I don't get your point, but you mean to use a `static mut`? Otherwise I cannot get the `thread-local RefCell` variable.

btw, I have tried importing `Isolate::get_current()`, it just returns nullptr  : (

**Comment by bnoordhuis** [comment]
Yes, that's right. Like this:
```rust
thread_local!(static ISOLATE: RefCell<Option<&'static mut Isolate>> = RefCell::new(None));

// set
ISOLATE.with(|slot| slot.replace(Some(unsafe { transmute(*isolate) })));

// get
ISOLATE.with(|slot| {
  if let Some(isolate) = &mut *slot.borrow_mut() {
    // ...
  }
});

// clear
ISOLATE.with(|slot| slot.replace(None));
```
Wrap it up in a type with RAII semantics and you have something that's pretty similar to `v8::Locker` or `v8::Isolate::Scope` from the C++ API.

**Comment by Icemic** [comment]
It works! Thank you @bnoordhuis @bartlomieju
