### ISSUE TITLE
compiler error under Rust 1.46 in const function

### ISSUE THREAD

**Issue by abnud1** [denoland/rusty_v8#472]
We're using rusty_v8 version 0.10 as v8 bindings to call javascript code from rust.  

We're also using Rust 1.46.0, yet a compiler error is thrown from rusty_v8 code, specifically from support.rs file. this is the compiler error:

> error[E0080]: could not evaluate constant
>    --> C:\Users\Administrator\.cargo\registry\src\github.com-1ecc6299db9ec823\rusty_v8-0.10.0\src\support.rs:596:5
>     |
> 596 |     [s][size_must_be_0]
>     |     ^^^^^^^^^^^^^^^^^^^ index out of bounds: the len is 1 but the index is 16
> 
> error[E0080]: could not evaluate constant
>    --> C:\Users\Administrator\.cargo\registry\src\github.com-1ecc6299db9ec823\rusty_v8-0.10.0\src\support.rs:590:22
>     |
> 590 |   const SELF: Self = Self::new_checked();
>     |                      ^^^^^^^^^^^^^^^^^^^ referenced constant has errors
> 

The OS Is Windows 10 x64.  

We tried downgrading Rust  to 1.45.0 but now we get errors about `#[track_caller]` attribute being experimental so we thought that rusty_v8 sure uses Rust version newer than 1.45 which is 1.46 right ? I don't think you require nightly right ?

The error message doesn't list anything from our code but we could be wrong too

**Comment by abnud1** [comment]
Ok I see that the result of this issue is passing a closure to `v8::Function::new` that captures variables from rust scope, the example found [here](https://github.com/denoland/rusty_v8/blob/fa8f636397822ba7dbb823d25dc637bf77f8b1ce/tests/test_api.rs#L1091-L1101) uses a closure without capturing any rust variables.

So how to capture rust variables? do I need to use `new_with_data` instead ? how to reference the data inside the closure then ?

**Comment by bnoordhuis** [comment]
Pretty much the same way you'd do it in C++: you store your closure somewhere, call `External::new(scope, raw_pointer)` and pass that to `Function::new_with_data(scope, callback, external.into())`. You retrieve it in your callback like this:
```rust
fn callback(scope: &mut Handlescope, args: FunctionCallbackArguments, rv: ReturnValue) {
  let external = Local<External>::try_from(args.data.unwrap()).unwrap();
  let raw_pointer: *mut std::ffi::c_void = external.value();  // explicit type for exposition
  // ...
}
```

**Comment by abnud1** [comment]
Thanks for your example, it now compiles
