### ISSUE TITLE
how to persist variables and functions created in a scope

### ISSUE THREAD

**Issue by abnud1** [denoland/rusty_v8#474]
We have two rust functions: one is for running void scripts and the other for executing a function already defined in global scope,

This is the implementation of runVoidScript:
```rust
    fn runVoidScript(isolate: &mut v8::OwnedIsolate,code: &str){
        let scope = &mut v8::HandleScope::new(isolate);
        let context = v8::Context::new(scope);
        let scope = &mut v8::ContextScope::new(scope, context);        
        let code = v8::String::new(scope, code).unwrap();

        let script = v8::Script::compile(scope, code, None).expect("failed to compile javascript code");
        script.run(scope).expect("runtime exception");
    }
```
in the other function we have code like this:
```rust
    fn runFunction(isolate: &mut v8::OwnedIsolate,function_name: &str){
        let scope = &mut v8::HandleScope::new(isolate);
        let context = v8::Context::new(scope);
        let scope = &mut v8::ContextScope::new(scope, context);
        let global = context.global(scope);
        // getting the javascript function whose name is function_name parameter   
        let function_name_string= v8::String::new(scope, function_name)
            .expect("failed to convert Rust string to javascript string");
        let function = global.get(scope, function_name_string.into()).expect(&*format!(
            "could not find function {}",
            function_name
        ));
        let function: v8::Local<v8::Function> = unsafe { v8::Local::cast(function) };
        // call that function with arguments
        let recv = v8::Integer::new(scope, 2).into();
        function.call(scope, recv, &[])
    }
```

The problem is if I execute runVoidScript with `runVoidScript(&mut isolate,"function test(){return 1;}")` then `runFunction(isolate,"test()")` I get "undefined is not a function" in the second code at the `function.call` line.

By googling I found that v8 c++ API has Persistent and according to issue #37 Persistent is already implemented but I don't see it in docs so where is it ? is it related to `Global` ? how to run javascript code in which all variables and functions defined top-level are persisted ? 

By the way the isolate parameter is the same isolate object, I don't expect nor want persistence to work across isolates

I also tried to store `Context` in a struct but that failed horribly, no matter how I try the borrow checker prevents me from doing that

**Comment by bnoordhuis** [comment]
> according to issue #37 Persistent is already implemented but I don't see it in docs so where is it ? is it related to `Global` ?

Yes. Mentally substitute `Persistent` with `Global` everywhere - that's the new name for it.

Background: `Persistent` had confusing copy semantics that made it easy to leak resources. V8 introduced `Global` with simple move semantics to address that. rusty_v8 only ever exposed `Global`, as far as I'm aware.

In your example, instead of creating a `Local<Context>` twice, you want to create it once and store it in a `Global<Context>`.

**Comment by abnud1** [comment]
Thank you very much, I'm sorry to disturb you with my questions , this library has really saved my day since compiling V8 from source is a head ache not to mention safe usage of its API
