### ISSUE TITLE
where is V8InspectorClient::new or how to create it

### ISSUE THREAD

**Issue by abnud1** [denoland/rusty_v8#476]
I need to use the V8 Inspector API to debug maximum call stack size reached issue in my javascript code, I saw the docs about the C++ API but I can't create V8InspectorClient object since I found no new or create or anything ?!!!

How to build that Object ?

**Comment by lucacasonato** [comment]
rusty_v8 does not provide an interface for the V8InspectorClient API right now.

**Comment by bnoordhuis** [comment]
Yeah, it's there but using it is pretty involved. You can find examples in the test suite:

https://github.com/denoland/rusty_v8/blob/9bedd96d2442dfbab5b83b6bb069de796e7273a5/tests/test_api.rs#L2913-L3157

rusty_v8 has to emulate C++ inheritance here, that's why it looks so peculiar.

**Comment by bnoordhuis** [comment]
I'll close this as answered but let me know if you have follow-up questions.
