### ISSUE TITLE
Wrapping Rust objects?

### ISSUE THREAD

**Issue by 3c1u** [denoland/rusty_v8#478]
Currently, `v8::External` is available for wrapping Rust objects as a `*mut c_void` pointer, and I feel a bit uncomfortable.

- Is it possible to add the type annotation for this?
Looking at the definition of `External` (and other types), however, there is no room for `std::marker::PhantomData<...>`.

- Is it possible to manage memory properly?
In C++, the memory de-allocation after the lifecycle is accomplished by the weak reference of `Persistent` handle and the callback. However, `rusy_v8` has no implementation for `Persistent` (and it seems to be intentional, as `Persistent` class is prone to be wrongly used).

- Is it possible to add lock mechanism for the pointer?
Accompanied with the type annotation, the Rust objects can be accessed "safely". (True, there will be overhead.)

**Comment by bnoordhuis** [comment]
> Is it possible to add the type annotation for this?

Not in general, I think. Restricting the type of a `v8::FunctionTemplate` receiver through a `v8::Signature` gives a modicum of runtime safety but that's not compile-time safety, of course.

> Is it possible to manage memory properly?

It's complicated. The GC may not ever reclaim a weakly persistent object so tying an external resource to such an object means you cannot rely on it being finalized.

> Is it possible to add lock mechanism for the pointer?

I'm not sure what you're asking.

**Comment by 3c1u** [comment]
>> Is it possible to add lock mechanism for the pointer?
>
> I'm not sure what you're asking.

I meant `Mutex` or `RefCell`-like things.

**Comment by gliheng** [comment]
In nodejs, object wrap provide a finalizer callback when js value is garbage collected. It's best rusty_v8 can provide similar ways to do this. Sometimes it would be cumbersome to let user manually call destructor when wrapped objects're not longer used. For example, `document.createElement('div')` creates a DOM element in native world. It feels natural that this object can be garbage collected without an explicit call to `remove`

**Comment by gliheng** [comment]
https://github.com/denoland/rusty_v8/pull/335  I found this pr is what I need. But haven't been merged yet.

**Comment by vstojkovic** [comment]
> Not in general, I think. Restricting the type of a `v8::FunctionTemplate` receiver through a `v8::Signature` gives a modicum of runtime safety but that's not compile-time safety, of course.

Is there a way to do this in rusty_v8? I've looked at both the docs and the source, and I couldn't find any way to create a `v8::Signature`, so I'm wondering if there's something I missed or it just isn't implemented yet.

**Comment by bnoordhuis** [comment]
@vstojkovic It's not implemented yet but I've opened #666. Ominous!

**Comment by devsnek** [comment]
In addition to signature, `v8::cppgc` now allows the use of typed/tagged embedder objects which participate in garbage collection.
