### ISSUE TITLE
why .a on android (aarch64) depend in exp@GLIBC2.17

### ISSUE THREAD

**Issue by zhuyijiang** [denoland/rusty_v8#479]
I can't run on Ubuntu 20.04 TLS OS system，because it's glibc version is 2.34；

**Comment by bnoordhuis** [comment]
Sorry, I must've missed the notification for this issue.

You're looking at symbol versioning. That symbol is - or should be - provided by later versions of libm (part of glibc.) `objdump -T /path/to/libm.so.6 | grep -w exp` ought to show at least one hit for `GLIBC_2.17`.

I'll close this out but let me know if you still have questions.
