### ISSUE TITLE
android ndk build 

### ISSUE THREAD

**Issue by zhuyijiang** [denoland/rusty_v8#480]
I run build librusty_v8.a ok in Ubuntu 20.04 TLS，but it‘s cpu tech is x86-64；

Please Help Me, What I should build if I Want build AArch64 version

commond line：V8_FROM_SOURCE=1 cargo ndk --platform 29 --target aarch64-linux-android build --release

Note: I find I build other program that is runnable in android phone.

**Comment by bnoordhuis** [comment]
See PR #270, aarch64-linux-android is not supported yet but it's being worked on.

I'll close this out but let me know if you have follow-up questions.

**Comment by moyy** [comment]
Hi，Have you a roughly Roadmap? when do you support aarch64-linux-android ? example: about 1-months, 2-months, or 6-months ?

May I have participate some develop in that quetion ?

**Comment by bnoordhuis** [comment]
I don't think there's an ETA for aarch64-linux-android support. Getting #270 merged is the first step, maybe you can help out with that?
