### ISSUE TITLE
[Question] Is rusty_v8::Script::compile leaking memory?

### ISSUE THREAD

**Issue by patrickpissurno** [denoland/rusty_v8#481]
Hi,

I looked everywhere (source-code, tests, docs, api reference, even into deno-core and deno-cli repos) but I just couldn't find a way to properly dispose a `Script` instance after execution. At first it seemed that it woudn't be necessary to do so, as I tought it'd be automatically disposed when going out of scope, but it seems it's not the case.

Am I missing something? Any tips on how to fix it?

Minimal example:
```rust
use rusty_v8 as v8;

fn main() {
    let platform = v8::new_default_platform().unwrap();
    v8::V8::initialize_platform(platform);
    v8::V8::initialize();

    let isolate = &mut v8::Isolate::new(Default::default());

    let scope = &mut v8::HandleScope::new(isolate);
    let context = v8::Context::new(scope);
    let scope = &mut v8::ContextScope::new(scope, context);

    let code = v8::String::new(scope, "Math.min(10, 20)").unwrap();

    loop {
        {
            let script = v8::Script::compile(scope, code, None).unwrap();
        }
        // I'd expect it to have been disposed by this line, but it is not
    }
}
```

**Caution when running the above example as in a few seconds it reached 2GB+ RAM usage on my machine.**

I'd argue that by going out of scope it should be automatically disposed, as there'd be no way of referencing that particular instance to call `run`, or even a (future) `dispose`-like method.

But if you don't feel like it's a good idea to automatically dispose it, you could at least provide a way of manually doing it.

It might not be something of utmost importance for Deno itself, as it uses modules and I've only seen a few calls to this particular function (I might be wrong, though), but for embedders it's very important.

I still can't figure out how Deno's REPL implementation works without leaking memory (if I could, I'd do it the same way). 

Despite my minimal example being a bit contrived, a REPL is a very real world-ish use-case that would constantly compile a new `Script` out of an input string, in a loop, thus leaking memory until an OOM exception finally halts the execution.

Any tips would be very appreciated. Also, I'm kinda new to Rust, so I apologize if I'm just being stupid.

Thanks!

**Comment by bnoordhuis** [comment]
Try this:
```rust
{
  let scope = &mut v8::HandleScope::new(scope);
  let script = v8::Script::compile(scope, code, None).unwrap();
  // ...
}
```
You can think of a `HandleScope` as a GC root container. Rooted values aren't garbage collected until the container goes out of scope.

In your example, all `Script` objects end up in a single `HandleScope` that lives forever.
