### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by MariusVB** [denoland/rusty_v8#483]
Build is failing when running `cargo install deno`.

First I got an error with "#[track caller]" experimental feature, but I found that the beta channel for rustc was needed to compile that. Now I've switched to the beta channel, but I'm receiving a new error:
![image](https://user-images.githubusercontent.com/24921111/94900481-59503900-0495-11eb-9859-dc035333aa54.png)

**Comment by bnoordhuis** [comment]
Try `rm -rf target/` - "truncated or malformed" probably means a corrupted libv8.a download.

**Comment by bnoordhuis** [comment]
Closing, but let me know if you're still having issues.
