### ISSUE TITLE
Property Interceptors

### ISSUE THREAD

**Issue by benaubin** [denoland/rusty_v8#503]
I'd love to be able to define property interceptors on objects.

I'm more than happy to write the implementation if it's something y'all want to merge. However, I haven't had much experience with C++, so I might need some guidance.

https://v8.dev/docs/embed#interceptors

**Comment by bnoordhuis** [comment]
Pull request welcome, let me know if you have questions.

`PropertyCallbackInfo` is already defined in src/function.rs, that should save you some work. :-)

**Comment by devsnek** [comment]
These are supported now.
