### ISSUE TITLE
Are there examples about js <--> rust call each other?

### ISSUE THREAD

**Issue by flyinmind** [denoland/rusty_v8#509]
I have not used v8 in c++, and examples in rusty_v8 are very simple.
So, I want to find some examples about  js and rust call each other,
and also transfer parameters each other.
Thanks!

**Comment by bnoordhuis** [comment]
`examples/process.rs` shows how to make JS -> Rust calls through function calls (`log_callback`) and property accesses (`request_prop_handler`.)

`tests/test_api.rs` is also a good resource. Here are two ways of making Rust -> JS calls:

https://github.com/denoland/rusty_v8/blob/fb049cb934dc7f417bd299b1c78d783a1e29bd6d/tests/test_api.rs#L1680-L1689 (construct call)

https://github.com/denoland/rusty_v8/blob/fb049cb934dc7f417bd299b1c78d783a1e29bd6d/tests/test_api.rs#L1760-L1766 (method call)

**Comment by flyinmind** [comment]
I'll try to understand it. Thanks!

**Comment by flyinmind** [comment]
still hang on

**Comment by bnoordhuis** [comment]
My pleasure! I'll close this out but let me know if you still have questions and I'll reopen.

**Comment by flyinmind** [comment]
From test_api.rs, I got so much.
There are still two questions, I can't find solutions from it.
1) How to bind a HashMap to js Object or Array?
2) How to bind a async-funtion in rust to js?

**Comment by bnoordhuis** [comment]
> How to bind a HashMap to js Object or Array?

You can probably make that work through a `Proxy` that calls your Rust API functions to get/set/query/etc. properties. #503 would let you do that more directly but hasn't been implemented yet.

> How to bind a async-funtion in rust to js?

You can't, not directly. You could perhaps devise some mechanism to glue the Rust `Future` to a JS `Promise` but that's well outside the remit of rusty_v8.

**Comment by flyinmind** [comment]
You can probably make that work through a Proxy that calls your Rust API functions to get/set/query/etc. properties. #503 would let you do that more directly but hasn't been implemented yet.

**Is there an example to show how to use Proxy?** 

You can't, not directly. You could perhaps devise some mechanism to glue the Rust Future to a JS Promise but that's well outside the remit of rusty_v8.

**How to glue a Rust Future to a JS Promise? If there is an example, that would be great ! Thanks!**
