### ISSUE TITLE
Need automated conversion for Local<String> to Local<Value>

### ISSUE THREAD

**Issue by ry** [denoland/rusty_v8#51]
Here is an attempted solution which doesn't quite work.

```rust
/// For example, to allow automated conversion from Local<String> to
/// Local<Value>
impl<'sc, T, U> From<Local<'sc, T>> for Local<'sc, U>
where
  T: Deref<Target = U>,
{
  fn from(v: Local<'sc, T>) -> Local<'sc, U> {
    unsafe { std::mem::transmute(v) }
  }
}
```

In C++ this is done by this bit of code: https://github.com/v8/v8/blob/63da8397bc967232f91fea07b1861a50d20ca717/include/v8.h#L192-L201

**Comment by manyuanrong** [comment]
I tried all kinds of ways. It seems that they are not feasible. I gave up for the time being.
Do we currently implement "From trait" for each "Local<T>" struct?

**Comment by manyuanrong** [comment]
We can use `macro_rules` to explicitly define the conversion relationships for these subtypes
```rust
macro_rules! impl_into_type {
    ($child:ident, $parent:ident) => {
        impl From<$child> for $parent {
            fn from(child: $child) -> $parent {
                unsafe { mem::transmute(child) }
            }
        }
    }
}
```

```rust
impl_into_type!(String, Value);
impl_into_type!(Boolean, Value);
impl_into_type!(Interger, Value);
```

**Comment by ry** [comment]
https://github.com/denoland/rusty_v8/commit/9a72f62bd661890088b1ea582e1f70ddd9fd76bd
