### ISSUE TITLE
Invalid result for serialzed Local<ArrayBuffer> with ValueSerializer::transfer_array_buffer

### ISSUE THREAD

**Issue by vmosone** [denoland/rusty_v8#513]
Invalid dst buffer after call ValueSerializer::transfer_array_buffer & ValueDeserializer::transfer_array_buffer.

Env:
Windows10 pro
rustc 1.47.0-nightly nightly-x86_64-pc-windows-msvc
rusty_v8 v0.12.0

Example:
from buffer: [97, 97, 97]
after transfer: [0, 0, 0]
Maybe this is the behavior? I don`t known.

Code slice:
```
use rusty_v8 as v8;
use v8::{ValueSerializerHelper, ValueDeserializerHelper};

let platform = v8::new_default_platform().unwrap();
v8::V8::initialize_platform(platform);
v8::V8::initialize();

let mut params = v8::Isolate::create_params();
let mut isolate = v8::Isolate::new(params);

let scope = &mut v8::HandleScope::new(&mut isolate);
let context = v8::Context::new(scope);
let scope = &mut v8::ContextScope::new(scope, context);

...
let buf: v8::SharedRef<v8::BackingStore> = ...;
let buf_len = buf.byte_length();
let src_buf = v8::ArrayBuffer::with_backing_store(scope, buf);
let mut serializer = v8::ValueSerializer::new(scope, ...);
serializer.transfer_array_buffer(0, src_buf);
let dst_buf = v8::ArrayBuffer::new(scope, buf_len);
let mut deserializer = v8::ValueDeserializer::new(scope, ..., &[]);
deserializer.transfer_array_buffer(0, dst_buf);
...
```

**Comment by bnoordhuis** [comment]
I think I understand your confusion. V8 has two modes for serializing ArrayBuffers: one where it simply copies its contents, and another where it stores a reference and the embedder (you) is responsible for transferring the backing store - that's where `serializer.transfer_array_buffer()` comes in.

**Comment by vmosone** [comment]
@bnoordhuis Thanks for you, I partially understand the problem.

But, I have another question，Whether origin ArrayBuffer will be set as unavailable after call serializer.transfer_array_buffer()?

**Comment by bnoordhuis** [comment]
You mean if the backing store gets detached automatically? No.

rusty_v8 doesn't support detaching at the moment but that could be added if needed, pull request welcome. The C++ API to bind to is `v8::ArrayBuffer::Detach()`.

**Comment by vmosone** [comment]
Alright.
I think I will try，thank you very much.
