### ISSUE TITLE
Potential hash collision by using v8::Module::GetIdentityHash()

### ISSUE THREAD

**Issue by ry** [denoland/rusty_v8#518]
https://github.com/denoland/deno/blob/1e5e091cb074896c7550b1b6f802582f12629048/libdeno/binding.cc#L293

Seems very unlikely people will hit this issue - but creating something just to track it.

**Comment by kitsonk** [comment]
These bindings are now in `rust_v8` so I moved it.

**Comment by bnoordhuis** [comment]
This is not for rusty_v8 to fix. The identity hash itself isn't buggy but it can be used in a way that introduces bugs.

To summarize:

1. An object's identity hash is a 21 or 22 bits random number (on 32 and 64 bits architectures respectively)

2. Per the Birthday Paradox, that means the chance of a collision is > 50% with approx. 1700 or 2400 objects.

You _can_ use it to store objects in a hashmap but you need to additionally check with `a.same_value(b)` if the object already exists in the hashmap bucket.
