### ISSUE TITLE
Support darwin-arm64

### ISSUE THREAD

**Issue by lucacasonato** [denoland/rusty_v8#520]
This will require us to have runners capable of darwin-arm64, or using QEMU.

**Comment by ry** [comment]
gn mistakenly thinks the host is x86_64 (I think because we use x86_64 gn binaries). To force arm64 build use
```
GN_ARGS="host_cpu=\"arm64\"" cargo build -vv
```

**Comment by ry** [comment]
Not supported in CI yet, but I've uploaded aarch64-apple-darwin binaries for v0.14.0
https://github.com/denoland/rusty_v8/releases/tag/v0.14.0

**Comment by YangtseSu** [comment]
> Not supported in CI yet, but I've uploaded aarch64-apple-darwin binaries for v0.14.0
> https://github.com/denoland/rusty_v8/releases/tag/v0.14.0

Maybe linux-aarch64 too.

**Comment by zhmushan** [comment]
windows too?

**Comment by frankhale** [comment]
I'm wondering if the latest release 0.18.2 will work on Arm64 Linux? Last Deno we could compile was 1.6.3 because there were rusty_v8 builds already prebuilt. With Deno 1.7 there hasn't been any prebuilt rusty_v8 builds so Deno won't compile.

**Comment by lucacasonato** [comment]
This is the tracking issue for macOS arm64.

**Comment by frankhale** [comment]
Yes I know but it's also mentioned Linux a couple replies up. I didn't want to create another issue.

**Comment by lucacasonato** [comment]
Well please create another issue, because this issue is not for tracking linux arm64, but for macOS.

**Comment by devsnek** [comment]
We are building darwin aarch64 now.
