### ISSUE TITLE
Compile rusty_v8 example on windows, fail to link, can't find v8__Isolate__SetPromiseHook...

### ISSUE THREAD

**Issue by flyinmind** [denoland/rusty_v8#524]
Cargo.toml
[dependencies]
rusty_v8="*"
futures = "*"

Code is modified from https://docs.rs/rusty_v8/0.12.0/rusty_v8/.
copy rust_v8.lib from https://github.com/denoland/rusty_v8/releases/download/v0.12.0/rusty_v8_release_x86_64-pc-windows-msvc.lib, and placed it under the directory "target/release/gn_out/obj"
Because in my environment, compile blocked when compiling rusty_v8.

When linking, prompt LNK2019/LNK2001.

LNK2019:unresolved external symbol 'symbol' referenced in function 'function'.
LNK2001:The symbol isn't defined in any libraries or object files searched by the linker

in my pc, can't read, because of vs-version;
error LNK2019: \xce\xde\xb7\xa8\xbd\xe2\xce\xf6\xb5\xc4\xcd\xe2\xb2\xbf\xb7\xfb\xba\xc5 v8__Isolate__SetPromiseHook\xa3\xac\xb8\xc3\xb7\xfb\xba\xc5\xd4\xda\xba\xaf\xca\xfd 

And other LNK2019/LNK2001
v8__Isolate__SetAllowAtomicsWait
v8__BigInt__New
v8__BigInt__NewFromUnsigned
v8__ValueDeserializer__TransferArrayBuffer
... total 64 errors

**Comment by bnoordhuis** [comment]
My best guess is that you downloaded an old .lib, probably v0.10, because those are all symbols that were added in the last two releases.

**Comment by flyinmind** [comment]
https://github.com/denoland/rusty_v8/releases/download/v0.12.0/rusty_v8_release_x86_64-pc-windows-msvc.lib

**Comment by flyinmind** [comment]
I found the following two versions **are the same.** **Are there some problems?**

https://github.com/denoland/rusty_v8/releases/download/v0.12.0/rusty_v8_release_x86_64-pc-windows-msvc.lib
https://github.com/denoland/rusty_v8/releases/download/v0.11.0/rusty_v8_release_x86_64-pc-windows-msvc.lib

**Comment by bnoordhuis** [comment]
I get different checksums:
```
$ sha1sum rusty_v8_release_x86_64-pc-windows-msvc.lib*
c3d54cf629064e29811b018bddfe8b19ff865c59  rusty_v8_release_x86_64-pc-windows-msvc.lib
f32305da5f6951dd92f097282241b74302c6cd96  rusty_v8_release_x86_64-pc-windows-msvc.lib.2
```
What checksums do you get?

**Comment by flyinmind** [comment]
Oh， puzzled， I have tried to download two times, they were all same sha1.
This morning, try again, they are not same. And compilation passed , happy and puzzled.
By the way, can aarch64 version be used in Android?
https://github.com/denoland/rusty_v8/releases/download/v0.12.0/librusty_v8_release_aarch64-unknown-linux-gnu.a

**Comment by bnoordhuis** [comment]
> By the way, can aarch64 version be used in Android?

Sadly, no. There's an open pull request but it stalled: #270
