### ISSUE TITLE
Support loading snapshots before snapshotting

### ISSUE THREAD

**Issue by NickGeek** [denoland/rusty_v8#551]
Hi,
I noticed that in `runtime.rs` there is a TODO around supporting loading snapshots and snapshotting on the same instance. It's a feature I'd find quite useful so I did some digging.

It looks like V8 supports receiving a `StartupData` in the constructor of `SnapshotCreator` ([source](https://source.chromium.org/chromium/chromium/src/+/master:v8/include/v8.h;drc=ed64b9822219f26660592ee5048418c1d4ade2a9;l=10025)). I tried naively updating `rusty_v8` to use that parameter, but I get an assertion failure:
```
# Fatal error in ../../../../v8/src/api/api.cc, line 636
# Debug check failed: data->created_.
```

Is there anything I can do to help get that todo item done?

**Comment by bartlomieju** [comment]
@NickGeek I've transferred the issue to `rusty_v8` repo as it must first be implemented here before we can add that feature to `deno` itself.

**Comment by bartlomieju** [comment]
@NickGeek please open a PR with your code; the error you got suggests that snapshot was not taken before dropping the isolate.

**Comment by NickGeek** [comment]
@bartlomieju Sweet, thanks. I'll try and get that up tonight. Just a warning: it's definitely in a draft state, I was mostly just seeing if I could get something to work.

**Comment by bartlomieju** [comment]
This is now supported.
