### ISSUE TITLE
V8Inspector::context_created should accept V8ContextInfo argument 

### ISSUE THREAD

**Issue by bartlomieju** [denoland/rusty_v8#552]
https://github.com/denoland/rusty_v8/blob/efe0e76a75603b70666297e9782ba01bd8ad0343/src/inspector.rs#L893-L895

It'd be quite useful if we could pass `V8ContextInfo` - it allows to set `origin` field which would help reduce some technical debt in `deno` related to REPL handling:

https://github.com/denoland/deno/blob/7135d34ccab7629da57c75ee239fcb0dda733eae/cli/module_loader.rs#L59-L64

https://github.com/denoland/deno/blob/7135d34ccab7629da57c75ee239fcb0dda733eae/core/module_specifier.rs#L58-L60

CC @bnoordhuis

**Comment by bnoordhuis** [comment]
@bartlomieju If you or @casparvonb want to work on this: rusty_v8 already doesn't follow the V8 C++ API here (because binding to C++ objects is Complicated) so feel free to simply extend `context_created()` with another parameter or change it to accept a struct.

**Comment by bartlomieju** [comment]
I'm gonna close this one, all arguments that can be passed to `V8ContextInfo` can now be passed directly to `context_created` function.
