### ISSUE TITLE
JavaScript APIs

### ISSUE THREAD

**Issue by Japroz-Saini** [denoland/rusty_v8#569]
Hi, can anyone pls give me an example on how to create your own JavaScript functions in this rusty_v8 library as I am new to v8. I want to create a function called log which can takes multiple arguements and print them like below
```javascript
log("hello","world");
//prints out 'hello world'
```

**Comment by bnoordhuis** [comment]
There are a bunch of examples in the `examples/` directory. If something's unclear, then please be specific.

**Comment by Japroz-Saini** [comment]
I saw the examples directory but the examples in there were kind of hard to understand. I just want to know how to create our own functions in `rusty_v8`

**Comment by ry** [comment]
@Japroz-Saini Here you go 
https://github.com/denoland/rusty_v8/blob/b19d0dc34941fa10ce6b3c31180bff6bf39d40c0/examples/process.rs#L147-L150

**Comment by Japroz-Saini** [comment]
Thank you @ry . Also, really happy that YOU replied to my issue. Actually, I am also creating a JavaScript engine. So thanku
