### ISSUE TITLE
mingw-32 windows build failed

### ISSUE THREAD

**Issue by Japroz-Saini** [denoland/rusty_v8#584]
Hi,My windows build failed while I ran the following commands:
```bash
rustup target add x86_64-pc-windows-gnu
cargo build --release --target x86_64-pc-windows-gnu
```
I even created a .cargo folder and created a config file but I got an error. File to small to be an archive

**Comment by bnoordhuis** [comment]
See #426, you need to use `x86_64-pc-windows-msvc` (different - incompatible - calling conventions.)

**Comment by Japroz-Saini** [comment]
So an you pls tell me what to write in the config file for `msvc` and what commands do I use to compile my software for windows .

**Comment by bnoordhuis** [comment]
I can't help you because your question is too vague to be actionable. What error or errors are you seeing and what steps did you take to get there? Please be precise and complete.

**Comment by Japroz-Saini** [comment]
I used this tutorial - https://github.com/BrooksPatton/learning-rust/wiki/cross_compiling
