### ISSUE TITLE
librusty_v8_release_aarch64-unknown-linux-gnu.a is gone

### ISSUE THREAD

**Issue by 06kellyjac** [denoland/rusty_v8#591]
In `0.16.0` `librusty_v8_release_aarch64-unknown-linux-gnu.a` isn't there.
`0.16.0`: https://github.com/denoland/rusty_v8/releases/tag/v0.16.0
`0.15.0`: https://github.com/denoland/rusty_v8/releases/tag/v0.15.0

~Is this a mistake or intentional?~ Removed due to sccache bug

Relevant PR and commit: #581 https://github.com/denoland/rusty_v8/commit/3a8cafb882144e9f5241097afde2dc11bfa8ae68

**Comment by lucacasonato** [comment]
This is currently intentional. We had to disable aarch64 linux builds due to an issue in CI. We are tracking reenabling the builds here: https://github.com/denoland/rusty_v8/pull/589

**Comment by 06kellyjac** [comment]
I'll close this in favor of #589 then :+1:
