### ISSUE TITLE
Add bindings for `ArrayBuffer::Detach` and friends

### ISSUE THREAD

**Issue by lucacasonato** [denoland/rusty_v8#646]
`ArrayBuffer::Detach` also requires `ArrayBuffer::Externalize` (because buf needs to have been externalized before detaching). `ArrayBuffer::IsDetachable` and `ArrayBuffer::IsExternal` would be very useful too.

**Comment by bnoordhuis** [comment]
`Externalize()` is deprecated in favor of `GetBackingStore()` but a binding for the latter already exists. (`IsExternal()` is deprecated for the same reason.)

I'll work on bindings for `Detach()` and `IsDetachable()` if you sign off on #645. :-)
