### ISSUE TITLE
Add bindings for `ArrayBuffer::New()` from existing memory block

### ISSUE THREAD

**Issue by lucacasonato** [denoland/rusty_v8#647]
For https://github.com/denoland/deno/issues/9799 we will need bindings for the third overload to `ArrayBuffer::New()` (the one that takes a data pointer, and byte_length, and creates an externalized `ArrayBuffer`).

Not sure what the ideal Rust signature for this would be. Maybe something along the lines of `ArrayBuffer::from_slice(slice: [u8])`?

**Comment by bnoordhuis** [comment]
That version of the ArrayBuffer constructor is deprecated in favor of the one that takes a BackingStore. A binding exists: `ArrayBuffer::with_backing_store()`

You can create an owned BackingStore with `ArrayBuffer::new_backing_store_from_boxed_slice()` (which takes a `Box<[u8]>`). Is that sufficient?

**Comment by lucacasonato** [comment]
I think so.
