### ISSUE TITLE
Context scope

### ISSUE THREAD

**Issue by chrsan** [denoland/rusty_v8#669]
Hi!

Sorry if this is the wrong place to ask questions, but google didn’t help me find any answers.

I’m new to v8 and haven’t been able to grasp when to use a `ContextScope`, and when it’s required? Does `HandleScope::with_context` create one implicitly?

When browsing the Deno source in the core crate a `ContextScope` is only used when setting up the bindings, but all v8 samples seem to use one.

Thanks in advance!

**Comment by bnoordhuis** [comment]
`v8::Context` is a JS execution context, complete with its own set of built-ins, like `Array`, `Object`, etc.

Scripts execute inside a context and `ContextScope` is how you select that context.

`HandleScope::with_context()` is a convenience function for activating an existing isolate and context. It doesn't create new ones.

**Comment by chrsan** [comment]
Thanks for the reply!

So if I have a `Global<Context>` setup created earlier (loaded from a snapshot for example) and then use `HandleScope::with_context` and only use what’s already bound in that context (i.e. inspecting objects etc through the API provided by this crate and not executing any scripts), I don’t need to create a `ContextScope` because the context from the `Global` is the active one?

**Comment by bnoordhuis** [comment]
Yes, that's right. Functionally, the `HandleScope::with_context()` call creates a `ContextScope` on your behalf.

**Comment by chrsan** [comment]
Great! Thanks
