### ISSUE TITLE
Regular STATUS_ACCESS_VIOLATION failures on Windows

### ISSUE THREAD

**Issue by lucacasonato** [denoland/rusty_v8#714]
It seems to happen about every 2-3 CI run.

Some examples:

- https://github.com/denoland/serde_v8/runs/2914613871
- https://github.com/denoland/deno/pull/11103/checks?check_run_id=2916551497

This also happens when just running rusty_v8 test suite standalone. No link to a failed CI run right now though.

**Comment by andreubotella** [comment]
The first time I saw this failure was on the first commit of #704. That PR doesn't seem to have anything obvious that might caused it, but at least it's an upper bound on when it was introduced.

**Comment by bnoordhuis** [comment]
The first time it happened on the main branch was 1e533a152e4231d72b7499c91fe8b2f66e3d5111, 1.5 week later.

**Comment by piscisaureus** [comment]
No idea what's causing this, but I can report that this only happens when testing in parallel (never happens with `--test-threads 1`), and that it does *not* seem to be related to a particular test. I suspect it might be a bug (race condition?) in `Isolate::dispose()`.
