### ISSUE TITLE
Implementation for PrototypeTemplate?

### ISSUE THREAD

**Issue by JomerDev** [denoland/rusty_v8#716]
Is there an implementation for PrototypeTemplate, or is there another way to achive it's functionality?

I wanted to wrap rust objects with rusty_v8, specifically to have objects with callable methods from js (for example a serial port with write and read methods). I found an v8 example which uses PrototypeTemplates to achive this. I only found Function- and ObjectTemplates in the rusty_v8 codebase, although there is a mention of PrototypeTemplates in a comment [here](https://github.com/denoland/rusty_v8/blob/main/src/data.rs#L519).

Is this something that just hasn't been implemented yet, or is there a different way to achive the same thing with rusty_v8?

**Comment by bartlomieju** [comment]
> Is this something that just hasn't been implemented yet, or is there a different way to achive the same thing with rusty_v8?

Yes, it hasn't been implemented yet as we had no need for it in Deno. PRs are more than welcome!

**Comment by Nathan1852** [comment]
Alright, thank you for the quick answer. I'll try and take a look at it
