### ISSUE TITLE
Publish under "v8" crate

### ISSUE THREAD

**Issue by ry** [denoland/rusty_v8#743]
https://crates.io/crates/v8 @dflemstr has graciously allowed us to use the "v8" crate name on crates.io

Probably we should continue to publish under rusty_v8 as well to avoid confusion. Unfortunately this seems a bit difficult...

rusty_v8 also has a special allowance on crates.io for larger package size. We would need that allowance also for the "v8" crate.

Maybe to start we should publish a README to "v8" crate pointing to rusty_v8?

**Comment by ry** [comment]
The quota for the "v8" crate has been increased by the crates.io staff. So this is no longer an issue.

**Comment by JayKickliter** [comment]
Can this be closed now?
