### ISSUE TITLE
Add bindings to serialise and deserialise WASM module objects

### ISSUE THREAD

**Issue by lucacasonato** [denoland/rusty_v8#759]
To support transferring WebAssembly modules between workers, I need following bindings:

- WasmModuleObject::GetCompiledModule
- WasmModuleObject::FromCompiledModule
- CompiledWasmModule

This carries with it the assumption that `CompiledWasmModule` is isolate agnostic and can be shared across threads. Is this correct? If not, I need `CompiledWasmModule::Serialize` too, and the reverse of that (what method is that?).

Ref https://github.com/denoland/deno/issues/11823

**Comment by andreubotella** [comment]
As far as I can tell, there isn't a public API to deserialize a compiled wasm module. And it's not very clear to me how Chromium transfers wasm module objects across isolates, but it does seem that they simply transfer the `CompiledWasmModule` object.
