### ISSUE TITLE
Clarify how the `MapFnTo` trait works

### ISSUE THREAD

**Issue by Rami-Sabbagh** [denoland/rusty_v8#763]
Hey, I've been learning rust and v8 very recently, and I got very confused when I stumbled by the `MapFnTo` trait while trying to construct a `FunctionTemplate`

![image](https://user-images.githubusercontent.com/6272475/131402144-63e6649a-e343-454f-8c09-7b23ba4668b8.png)

Following the definition of `FunctionCallback`

```rs
pub type FunctionCallback = extern "C" fn(_: *const FunctionCallbackInfo);
```

The documentation of `MapFnTo` says nothing about the trick it does.

The only hint that I got was to provide a rust function which takes the `FunctionCallBackInfo` parameter, and that doesn't work.

After digging in the source-code of this crate, found out about the other `MapFnFrom` trait which completes the trick.

And is implemented for `FunctionCallback`, `PerpareStackCallback` and `ResolveModuleCallback`

So that rust function with specific different signatures than the C types, are magically mapped.

```rs
// For `impl MapFnTo<FunctionCallback>` it would be a rust function of:
fn rust_function_callback(
    handle: &mut v8::HandleScope,
    args: v8::FunctionCallbackArguments,
    ret: v8::ReturnValue
) {
    //...
}
  
// For `impl MapFnTo<PrepareStackCallback>`
fn rust_prepare_stack_callback(
    handle: &mut v8::HandleScope,
    _: v8::Local<v8::Value>,
    _: v8::Local<v8::Array>
) {
    //...
}

// For `impl MapFnTo<ResolveModuleCallback>`
fn rust_resolve_module_callback(
    context: v8::Local<v8::Context>,
    _: v8::Local<v8::String>,
    _: v8::Local<v8::FixedArray>,
    _: v8::Local<v8::Module>
) {
    //...
}
```

It would be very nice if the documentation can clarify those functions signatures so other's don't have to fall into the same pit I had to dig it 😓

**Comment by bnoordhuis** [comment]
Documentation pull request welcome. Not sure what it should say because you don't normally interact with `MapFnTo` directly. It creates the `extern "C"` function trampoline that calls your handler.
