### ISSUE TITLE
Static library download

### ISSUE THREAD

**Issue by chrsan** [denoland/rusty_v8#764]
I'm getting `403` errors from `./tools/download_file.py` when trying to build
using version 0.26 and 0.27 on Mac OS X 10.15.7. A quick search on Google suggests
that this may be due to missing headers such as `User-Agent`. After 3 retries falling back
to cURL everything works just fine.

**Comment by bnoordhuis** [comment]
I just tried and it works fine for me. Maybe something on your end? Are you still experiencing this issue?
```
$ python tools/download_file.py --filename librusty_v8_release_x86_64-unknown-linux-gnu.a --url https://github.com/denoland/rusty_v8/releases/download/v0.27.0/librusty_v8_release_x86_64-unknown-linux-gnu.a
Downloading https://github.com/denoland/rusty_v8/releases/download/v0.27.0/librusty_v8_release_x86_64-unknown-linux-gnu.a... Done.

$ python tools/download_file.py --filename librusty_v8_debug_x86_64-unknown-linux-gnu.a --url https://github.com/denoland/rusty_v8/releases/download/v0.27.0/librusty_v8_debug_x86_64-unknown-linux-gnu.a
Downloading https://github.com/denoland/rusty_v8/releases/download/v0.27.0/librusty_v8_debug_x86_64-unknown-linux-gnu.a... Done.
```

**Comment by chrsan** [comment]
I'm sure it is, but I've been having this issue for a couple of days now. With cURL everything works just fine. Maybe an env setting to prefer cURL would be nice. I get the same error using both the bundled Python 2.7.16 and with Python 3.9.6 via Homebrew.

**Comment by bnoordhuis** [comment]
Someone else wasn't able to reproduce this either (on a M1) so it does look like something on your end.

> Maybe an env setting to prefer cURL would be nice.

I sympathize but I don't really want to make changes when the cause is poorly understood.

**Comment by chrsan** [comment]
Cool! I’ll investigate further and see if I can find what’s causing this behavior on my machine.
