### ISSUE TITLE
`Isolate::set_host_import_module_dynamically_callback` is unsound

### ISSUE THREAD

**Issue by y21** [denoland/rusty_v8#790]
This function takes a [`HostImportModuleDynamicallyWithImportAssertionsCallback`](https://docs.rs/rusty_v8/0.30.0/rusty_v8/type.HostImportModuleDynamicallyWithImportAssertionsCallback.html). It's a callback that is called to resolve `import()`s, and should return a *raw* pointer to a `v8::Promise`.
Its safety invariants are (sort of) mentioned in the docs, however there is nothing stopping the embedder from creating UB in safe Rust using this API due to the unchecked raw pointer that V8 will read and reinterpret as a `v8::Promise`.
~~If we can't check for correctness of the returned pointer, perhaps we could mark this function unsafe?~~

Minimal working example:
```rs
#![forbid(unsafe_code)]
use rusty_v8 as v8;

fn main() {
    let platform = v8::new_default_platform(0, false).make_shared();
    v8::V8::initialize_platform(platform);
    v8::V8::initialize();

    extern "C" fn import(
        _: v8::Local<v8::Context>,
        _: v8::Local<v8::ScriptOrModule>,
        _: v8::Local<v8::String>,
        _: v8::Local<v8::FixedArray>,
    ) -> *mut v8::Promise {
        // Returning an invalid pointer
        1337usize as *mut _
    }

    let mut isolate = v8::Isolate::new(Default::default());
    isolate.set_host_import_module_dynamically_callback(import);

    let mut scope = v8::HandleScope::new(&mut isolate);
    let context = v8::Context::new(&mut scope);
    let mut scope = v8::ContextScope::new(&mut scope, context);

    let code = v8::String::new(&mut scope, "import('hi')").unwrap();

    let script = v8::Script::compile(&mut scope, code, None).unwrap();
    script.run(&mut scope).unwrap();
}
```
```sh
$ cargo r
Segmentation fault (core dumped)
```

**Comment by piscisaureus** [comment]
Agreed that this is a bug. We should change the callback signature exposed in the public API so that it returns a `Local<Promise>`. The callback can be internally wrapped in a C style callback using the `MapFnTo` trait.

**Comment by bartlomieju** [comment]
This appears to be fixed as `HostImportModuleDynamicallyCallback` has return type of `Option<Local<Promise>>`
