### ISSUE TITLE
Add bindings for `AllowJavascriptExecutionScope`

### ISSUE THREAD

**Issue by andreubotella** [denoland/rusty_v8#833]
In denoland/deno#12505 it came up that trying to run Javascript code from [`v8::ValueDeserializerImpl::read_host_object`](https://docs.rs/v8/0.34.0/v8/trait.ValueDeserializerImpl.html#method.read_host_object) resulted in a crash because apparently that method is invoked from V8 inside a `DisallowJavascriptExecutionScope`. Implementing structured clone for web APIs in Deno essentially requires running JS code in the implementation of that method, and so bindings to [`v8::Isolate::AllowJavascriptExecutionScope`](https://source.chromium.org/chromium/chromium/src/+/main:v8/include/v8-isolate.h;l=338) would be needed to make that possible.

**Comment by piscisaureus** [comment]
@piscisaureus cc self
