### ISSUE TITLE
How to store persistent scope

### ISSUE THREAD

**Issue by joehoyle** [denoland/rusty_v8#848]
I'm trying to understand how to store rust_v8 scope in a Struct (or otherwise) to allow later execution of JS in the same scope later in the program. A very similar question was asked here: https://users.rust-lang.org/t/using-rusty-v8-how-to-create-a-persistent-scope/48998 but never answered.

I've been looking around for examples, but haven't found anything, the closest example is the shell program, however that uses a `while` loop (https://github.com/denoland/rusty_v8/blob/main/examples/shell.rs#L33-L49) so is able to keep all the scope / context variables alive and in-scope. I'm essentially trying to do something like this:

```rust

struct JSRuntime {
    isolate....,
    scope...., etc
}

impl JSRuntime {
    pub fn new() -> Self {
        // create isolate and scope etc
    }
    pub fn execute_string(&mut self, code: &str) {
        let code = v8::String::new(self.scope, str).unwrap();
        let script = v8::Script::compile(self.scope, code, None).unwrap();
        let result = script.run(scope).unwrap();
    }
}
```

Whereby subsequent calls to `execute_string` will evaluate in the same scope, so I could do:

```rust
jsruntime.execute_string("let foo = 'bar'");
jsruntime.execute_string("console.log(foo)");
```

If anyone has seen examples or guidance on this I would be super happy! I am very new to Rust, and have been trying to work out how to store owned variables in the struct that reference other values in the struct, but things are not coming together very well!

**Comment by bnoordhuis** [comment]
> I'm trying to understand how to store rust_v8 scope in a Struct

The short answer is "you don't" - V8's (not rusty_v8's) HandleScopes are intended to be stack allocated. rusty_v8 just enforces it more strongly than V8 does.

I _think_ what you're asking is how to keep a JS evaluation context around and that's by:

1. storing it in a `v8::Global<v8::Context>`,
2. turning it into a value again with `v8::Local::new()`, and
3. entering it with `v8::ContextScope::new()`.

**Comment by joehoyle** [comment]
Ah thanks @bnoordhuis! I was able to take what you said and also found this example by @abnud1 at https://github.com/abnud1/rust-ssr/blob/main/src/ssr.rs#L51-L57 too! Thanks again for the help
