### ISSUE TITLE
v8::script_compiler::Source.get_cached_data can lead to crash

### ISSUE THREAD

**Issue by RomainMuller** [denoland/rusty_v8#884]
The `cached_data` property of `v8::ScriptCompiler::Source` is optional/nullable. A proof of this is how `v8::script_compiler::Source` has two constructors (one with cached data, and one without).

Constructing a `Source` value without cached data will lead to `get_cached_data` returning an invalid `CachedData` value (i.e: `null`).

https://github.com/denoland/rusty_v8/blob/729c5b323f5bd172056a240c4bd9d9639b79be66/src/script_compiler.rs#L146-L148

That accessor should return `Option<&CachedData>`, I think?

**Comment by bartlomieju** [comment]
@RomainMuller yes, that sounds good. PRs are welcome!
