### ISSUE TITLE
Value::TypeOf is not exposed from v8

### ISSUE THREAD

**Issue by TimDiekmann** [denoland/rusty_v8#957]
v8 provides [`Value::TypeOf`](https://v8.github.io/api/head/classv8_1_1Value.html#a1f6e02579b0ddd7d223dd37bfea728d6) but this is not exposed in rusty_v8. Is it possible that this could be added?

**Comment by bartlomieju** [comment]
Yes, it could be added. PRs are welcome!

**Comment by bartlomieju** [comment]
Done in #1133
