### ISSUE TITLE
Avoid creating a reference to uninitialized `T` when calculating offsets

### ISSUE THREAD

**Issue by y21** [denoland/rusty_v8#958]
https://github.com/denoland/rusty_v8/blob/64ce32392a680695975a7d40921f11d1e4bbf7c5/src/inspector.rs#L275-L281

https://github.com/denoland/rusty_v8/blob/64ce32392a680695975a7d40921f11d1e4bbf7c5/src/inspector.rs#L538-L544

The call to `.base()` here on line 281 (and line 544) creates a reference to an uninitialized `T`, because `base()` is defined to take `&self` as its receiver. This is said to be UB by the documentation of [`MaybeUninit::as_ptr()`](https://doc.rust-lang.org/stable/std/mem/union.MaybeUninit.html#method.as_ptr):
> Gets a pointer to the contained value. Reading from this pointer or **turning it into a reference is undefined behavior unless the MaybeUninit<T> is initialized**

I'm not sure what the best way is to fix it: we cannot change the receiver to `self: *const Self` because that requires the nightly feature `arbitrary_self_types`.
Just changing it to not take a receiver at all, and instead using some other identifier as its parameter (e.g. `this: *const Self`) makes the trait not object safe and that breaks `ChannelBase`' rust_vtable field:
https://github.com/denoland/rusty_v8/blob/64ce32392a680695975a7d40921f11d1e4bbf7c5/src/inspector.rs#L258

We could make `base` and `base_mut` methods require `Self: Sized` so a `&dyn ChannelImpl` doesn't have those two methods, and I'm not sure if `rust_vtable` really *needs* `base` and `base_mut` methods, and if it doesn't, that might be a viable solution, i.e.
```rs
pub trait ChannelImpl: AsChannel {
  fn base(this: *const Self) -> *const ChannelBase where Self: Sized;
  fn base_mut(this: *mut Self) -> *mut ChannelBase where Self: Sized;
}
```
Then we can do what the `get_offset_within_embedder` methods do, without the reference:
```rs
let buf = std::mem::MaybeUninit::<T>::uninit(); 
let embedder_ptr: *const T = buf.as_ptr();
let base: *const Self = T::base(embedder_ptr);
```
Alternatively we could add another method, `base_ptr`, that has the same signature as `base` above, and keep `base()` and `base_mut()` as it is, so
```rs
pub trait ChannelImpl: AsChannel {
  fn base(&self) -> &ChannelBase;
  fn base_mut(&mut self) -> &mut ChannelBase;
  fn base_ptr(this: *const Self) -> *const ChannelBase where Self: Sized;
}
```
that we could then use in the `get_offset_within_embedder` methods like above.

Or lastly, we could *just* initialize it with dummy data (e.g. a null pointer). 

------
*Relevant PR: #954*

**Comment by bartlomieju** [comment]
Is this still a problem with #954 landed @y21?

**Comment by y21** [comment]
I don't think this is fixed yet, at least the linked PR didn't fix this. The problematic code is still there today. This creates an uninitialized `T`:
https://github.com/denoland/rusty_v8/blob/d4931dc8913cfe193ceca9c4f3819f606fed76d5/src/inspector.rs#L286-L287
And then a reference to the uninitialized `T` is created by the call to `base()`: 
https://github.com/denoland/rusty_v8/blob/d4931dc8913cfe193ceca9c4f3819f606fed76d5/src/inspector.rs#L290


I don't know what the best way to fix this would be since I'm not even really sure what this trait is mainly used for. I just found those problematic instances of `MaybeUninit` while working on the linked PR ^^. But, without knowing anything about the `ChannelImpl` trait, to me it seems like the "best" solution would be to add a new method to the trait: `fn base_ptr()`, that does pretty much the same thing as `fn base()` but works with pointers, so there are no invalid references being created?

**Comment by WingZer0o** [comment]
Anyone mind if I take this up with @y21's suggested solution?

**Comment by bartlomieju** [comment]
> I don't know what the best way to fix this would be since I'm not even really sure what this trait is mainly used for.

@y21 I believe this trait is used to simulate the virtual class that is required here 

@WingZer0o please do

**Comment by WingZer0o** [comment]
@y21 I am hoping I am point you in the totally wrong direction. So, this section is related to the V8 Inspector V8 api. https://v8.dev/docs/inspector as the embedder we are communicating with V8 for debugging support in this situation. My interruption is we are creating the trait for the Channel to be sending and receiving messages between the embedder and V8.

**Comment by WingZer0o** [comment]
We are working with two different traits in this case, so changes to one will not apply to both as I currently just tried. 

```Rust
  fn get_offset_within_embedder<T>() -> FieldOffset<Self>
  where
    T: V8InspectorClientImpl,
  {
    let buf = std::mem::MaybeUninit::<T>::uninit();
    let embedder_ptr: *const T = buf.as_ptr();
    let self_ptr: *const Self = unsafe { (*embedder_ptr).base() };
    FieldOffset::from_ptrs(embedder_ptr, self_ptr)
  }
```

**Comment by WingZer0o** [comment]
It seems our best course of action would be to use 

```Rust
fn base_ptr(this: *const Self) -> *const ChannelBase where Self: Sized;
```

If I adjust the following the usage of these methods change outside of these uninitialized T changes.

```Rust
impl<T> AsChannel for T
where
  T: ChannelImpl,
{
  fn as_channel(&self) -> &Channel {
    &self.base().cxx_base
  }
  fn as_channel_mut(&mut self) -> &mut Channel {
    &mut self.base_mut().cxx_base
  }
}
```

**Comment by y21** [comment]
Seems like this is fixed now.
