### ISSUE TITLE
static librusty_v8.a is huge

### ISSUE THREAD

**Issue by piscisaureus** [denoland/rusty_v8#974]
The sizes of the rusty_v8 binary distribution has exploded after the recent V8/toolchain upgrade.

* `librusty_v8_debug_aarch64-apple-darwin.a`: 131mb -> 3.5gb
* `librusty_v8_release_aarch64-apple-darwin.a`: 50mb -> 3.8gb

On x64 and linux the situation is the same. Windows seems unaffected.

Regardless of what caused the size jump, I think that using a "traditional" archive file with multiple objects files in it must be very wasteful, because v8 makes heavy use of templates that are shared between .cc files.

We should attempt to "pre-link" these separate object file into a single object file, in order to get rid of all this duplicate code.
We can put the pre-linked object file in an archive by itself, so downstream consumers won't notice a difference.

On mac-arm64 the following works:

```
piscisaureus@dumbo:~/d/rusty_v8/target/debug/gn_out 🦕 export DIST_NAME=librusty_v8_debug_aarch64-apple-darwin
piscisaureus@dumbo:~/d/rusty_v8/target/debug/gn_out 🦕 ld -r -arch arm64 -keep_private_externs -force_load ./obj/librusty_v8.a -o obj/$DIST_NAME.o 
piscisaureus@dumbo:~/d/rusty_v8/target/debug/gn_out 🦕 rm -f $DIST_NAME.a
piscisaureus@dumbo:~/d/rusty_v8/target/debug/gn_out 🦕 ar -rcs ./$DIST_NAME.a obj/$DIST_NAME.o
```

Result:

```
piscisaureus@dumbo:~/d/rusty_v8/target/debug/gn_out 🦕 ls -lh *.a obj/*.a    
-rw-r--r--  1 piscisaureus  staff    79M May 18 16:04 librusty_v8_debug_aarch64-apple-darwin.a  # After
-rw-r--r--  1 piscisaureus  staff   3.8G May 18 16:00 obj/librusty_v8.a                         # Before
```

Check:

```
piscisaureus@dumbo:~/d/rusty_v8 🦕 mv ./target/debug/gn_out/librusty_v8_debug_aarch64-apple-darwin.a /tmp
piscisaureus@dumbo:~/d/rusty_v8 🦕 export RUSTY_V8_ARCHIVE=/tmp/librusty_v8_debug_aarch64-apple-darwin.a
piscisaureus@dumbo:~/d/rusty_v8 🦕 unset V8_FROM_SOURCE
piscisaureus@dumbo:~/d/rusty_v8 🦕 rm -rf target
piscisaureus@dumbo:~/d/rusty_v8 🦕 cargo test   
(it works, all the tests pass)
```

Now the next steps are:

- [ ] This pre-link step needs to be part of our build, so I think it needs to be translated to a gn custom_action.
- [ ] Figure out how to do it on Linux.
- [ ] Maybe on Windows too...? It's not so urgent because the size of `rusty_v8.lib` didn't jump.

**Comment by andreubotella** [comment]
I tried commenting out [the removed configs](https://github.com/denoland/rusty_v8/blob/main/BUILD.gn#L13-L16) in `BUILD.gn`, and on a debug build in Linux x64 it brings the size down from 1.5 GB to 11 MB without breaking the rusty_v8 tests. It also doesn't affect the build time from scratch significantly.

**Comment by piscisaureus** [comment]
> I tried commenting out [the removed configs](https://github.com/denoland/rusty_v8/blob/main/BUILD.gn#L13-L16) in `BUILD.gn`, and on a debug build in Linux x64 it brings the size down from 1.5 GB to 11 MB without breaking the rusty_v8 tests. It also doesn't affect the build time from scratch significantly.

We can't use thin archives because they are not self-contained. It'll work fine on your system but not for anybody else

**Comment by piscisaureus** [comment]
Turns out that relocatable linking on mac comes with a number of caveats, the most important one being that all debug info is lost. I updated the flags in order to get the same debuginfo level as we had before the latest V8+toolchain upgrade, but otherwise nothing has changed.
