### ISSUE TITLE
is there a version for ios 

### ISSUE THREAD

**Issue by Charlieatinstinct** [denoland/rusty_v8#989]
I am planning to build a deno runtime on an iPhone, basically, I need a rusty_v8 of ios version, but I didn't find it on the release list, I also tried to find one on google, and still got nothing valuable information. Please, any suggestions would be appreciated

**Comment by waterbang** [comment]
me too

**Comment by lucacasonato** [comment]
`rusty_v8` does not support iOS right now. This is not something that we can spend engineering resources on right now, but we'd be happy to land a PR to make it work as a secondary target (like the Android support in `rusty_v8`).
